### PR TITLE
Add abcbox to common.js lib

### PR DESCRIPTION
**Pull request by BenGig**
A piece of code I got years ago and modified slightly. I use it to create structured library listings which are comfortable to browse on devices with limited scrolling capabilities.

### CODE REVIEW

**Comment by v00d00** [comment]
Hi, thanks for the patch! can you describe what it does a bit more?

**Comment by BenGig** [comment]
It can be used to create virtual folders which split collections into alphabetic groups. Example for box type 9 to create a list of artist folders. The content of my artists folder looks like this (genre, albums are similar):

--all--
-0-9-
-ABCDE-
    A        <-- one level lower
    B
    C
    ...
 -FGHIJ-
 -KLMNO-
 -PQRS-
 -T-           <-- tends to be big
 -UVWXYZ-
 -^&#'!-

Additional code to create the virtual folder chain in import.js:

chain = new Array('-Artist-',  '--all--', artist);
obj.title = title + ' (' + album + ', ' + date + ')'; 
addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ARTIST);
chain = new Array('-Artist-', abcbox(artist, 9, '-'), '-all-', artist);
obj.title = title + ' (' + album + ', ' + date + ')'; 
addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ARTIST);
chain = new Array('-Artist-', abcbox(artist, 9, '-'), artist.charAt(0).toUpperCase(), artist, '-all-');
obj.title = title + ' (' + album + ', ' + date + ')'; 
addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ARTIST);

I may create a more extensive example of a import.js, but have to remove some particularities from my production file. It has extensively adapted.

**Comment by BenGig** [comment]
browsing levels a bit more visualized

* --all--
* -0-9-
* -ABCDE-
  * A
    * ABC
    * -all-
      * How to be a Zillionaire (1985)
      * The Lexicon of Love (1985)
  * B
  * C

**Comment by v00d00** [comment]
Ah nice, that is certainly useful!

Any chance of adding a little to the sphinx documentation similar to the above and how to use it?

**Comment by elmodaddyb** [comment]
I have been interested in adding some javascript specs to the **node-js** tests for these scripts.  I'll try to see what I can create for the method attached.

**Pull request merged**
