### PR TITLE
Web UI: Ship Lato font, use full Gerbera logo

### PR DESCRIPTION
**Pull request by v00d00**
This is what it looks like now, only cosmetic, all the tests pass.

image

### CODE REVIEW

**Comment by v00d00** [comment]
@elmodaddyb please merge if you are happy.

Also, can I run the mock server (to dev with) without running the full e2e?

**Comment by v00d00** [comment]
New icons:
image

**Comment by elmodaddyb** [comment]
Totally AWESOME!!!!!!!! :1st_place_medal:

**Comment by elmodaddyb** [comment]
I will merge this, just waiting on the travis-ci :timer_clock:

**Comment by elmodaddyb** [comment]
@v00d00 - you can definitely run the mock server concurrently.  You can run the `npm` commands from the `gerbera-web` root directory.

## Running Mock Server

```
[whoami@localhost gerbera-web]$ npm start

> gerbera-web@0.0.2 start /development/gerbera/gerbera-web
> node index.js

Mock webserver listenting on : 3000
```
You can focus a unit test with jasmine using `fdescribe(...)` and ignore using `xdescribe(...)`.  The E2E use mocha since they are running server side.  You can focus a E2E using `test.it.only(...)` and ignore using `test.it.skip(...)`

> I usually focus on a single e2e and test using `test.describe.only(...)` since each **spec** has some sequently flow dependency.

## Adding to the Mock Server

`/gerbera-web/mock-api` contains the stubs for all the Gerbera `content/interface` endpoints.

`/gerbera-web/mock-api/routes.js` is a global routes file that sends all traffic to the proper mock based on the endpoint requested.

`./tests/*.json` is a container for each mock stub that explicitly defines the sequence of mocks to return when the URL is called upon.

Each E2E then defines the **test** to run before cycling through the behavior.
```
driver.get(mockWebServer + '/reset?testName=items.spec.json')
```
The mock-api is growing in size, so likely needs a bit of refactoring at this point to DRY it up.

**Comment by v00d00** [comment]
Heh, I was already using the mock server actually, I just didnt realise you had to log in :laughing: :blush:

**Pull request merged**
