### PR TITLE
deque removal

### PR DESCRIPTION
**Pull request by neheb**
No benefit over vector here. Small size reduction.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
Im 99% sure you converted this from `vector` to `deque`

**Comment by neheb** [comment]
At the time push_front was being used. It seems that since then it has been reworked to not so that.

**Comment by cweiske** [comment]
Doesn't that make #2351, #2350 and this here useless?
Just keep the semantically correct types and do not care how they are implemented under the hood, since this can change tomorrow.

**Comment by neheb** [comment]
There's no benefit to deque here. It's slower than vector. push and pop_front were removed at some point.

**Comment by KarlStraussberger** [comment]
I don't see the need for deque here but remind everybody to improve code by functionality and resource consumption (time and storage) as well. Everybody's time is too valuable to discuss a change in container types. Anyway, even small changes in the container type may break things.

**Pull request merged**
