### PR TITLE
fix bugs in addFfmpegMetadataFields()

### PR DESCRIPTION
**Pull request by mlaerd**
I found 2 bugs in FfmpegHandler::addFfmpegMetadataFields().

1. Because both propertyMap.second and FFMpeg::metadata->key are `const char *`, we need to use `strcmp()` instead of `==`.
2.  If the metadata which is not included in `propertyMap` is found after this method processed M_TRACKNUMBER (or M_PARTNUMBER), `item->setTrackNumber(stoiString(value));` is called again incorrectly because `field` is still `M_TRACKNUMBER`.

I fixed the bugs and confirmed metadata of DSF file are set to DB correctly.

### CODE REVIEW

**Comment by neheb** [comment]
First bug was introduced with https://github.com/gerbera/gerbera/commit/3f5ccd68bacc24c489b23ab4a7ecf1b5483bd7b7

I wonder if it would make more sense to turn the pair from const char * to std::string_view. Would allow == to work again.

**Comment by mlaerd** [comment]
@neheb 
Thanks for your comment.
I found [std:string provides operator== for const char*](https://stackoverflow.com/questions/2931704/how-to-compare-string-with-const-char) and updated the code.
I confirmed it works.

**Comment by mlaerd** [comment]
I want to rerun checks. Could someone help me?

**Comment by neheb** [comment]
git rebase origin/master
git push --force

**Comment by mlaerd** [comment]
@neheb 
Thanks a lot!

**Comment by whyman** [comment]
Nice patch, thanks!

**Pull request merged**
