### PR TITLE
convert Quirks to unique_ptr

### PR DESCRIPTION
**Pull request by neheb**
Avoids copies.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
Avoids copies how?

**Comment by whyman** [comment]
I actually think removing this pointer could work here, assuming those are the only accesses.

Assuming that all get calls are const refs, it shoud be fine.

**Comment by neheb** [comment]
unique_ptr has a deleted copy constructor/operator.

shared_ptr is a lot more complex than just allowing copies. It also does ref counting, which is pointless in this case.

**Comment by whyman** [comment]
Huh?

**Comment by neheb** [comment]
Tried removing the unique_ptr, too many build failures.

It's easier to keep as is.

**Pull request merged**
