### PR TITLE
Enable editing mime-type for externalUrl (fixes #790)

### LINKED ISSUE #790: Web-UI: Add External URL forces mimetype
Hi,

I've been trying to add my Tvheadend livestreams as `external links` in Gerbera, but unfortunately this seems to force the mimetype to `application/octet-stream`. This works on my new DLNA devices but does not work on my older ones.

I also captured some live TV footage and stored them as `.mp4`[HD] and `.m2ts`[SD]. Those played fine on all devices when the Mimetype was set to `video/mpeg`. This implies that my devices support the necessary codecs.

After searching the internet for a while I stumbled on this [MediaTomb result](https://tvheadend.org/boards/5/topics/12850) where they seem to accomplish something similar.

_Here is a picture of the issue I'm facing, after adding the virtual file the Mimetype is changed and cannot be modified._
Knipsel

### PR DESCRIPTION
**Pull request by KarlStraussberger**
Seems a straightforward change in Javascript code. Server code seems capable of changing mime type.
Code is backward compatible with Gerbera 1.4.0

### CODE REVIEW

**Comment by whyman** [comment]
Nice! Does this only affect `externalUrl`?

**Comment by whyman** [comment]
Can you update the tests too please?

**Comment by KarlStraussberger** [comment]
Took me some time to set up the test environment on my openSuSE box

**Comment by whyman** [comment]
@KarlStraussberger no rush, thanks!

**Pull request merged**
