### PR TITLE
introduce io-handler tell

### PR DESCRIPTION
**Pull request by pamapa**
Idea:
This feature will allow in a next step to simplify the MetadataHandler::serveContent function:
```
zmm::Ref<IOHandler> MetadataHandler::serveContent(zmm::Ref<CdsItem> item, int resNum, off_t* data_size)
```

Simpler:
```
zmm::Ref<IOHandler> MetadataHandler::serveContent(zmm::Ref<CdsItem> item, int resNum)
```
-> the data_size can be calculated via seek + tell, e.g.
```
io_handler = _MetadataHandler.serveContent()_

// get size
io_handler->open(UPNP_READ);
io_handler->seek(0L, SEEK_END);
off_t size = io_handler->tell();
io_handler->close();
```

### CODE REVIEW

**Comment by pamapa** [comment]
works for me now

**Comment by pamapa** [comment]
would be nice to have this merged now

**Comment by whyman** [comment]
Hey, can you rebase this? Then will merge straight away

**Comment by pamapa** [comment]
its now up with master + i have replaced ftell with ftello (for 32bit os)

**Comment by whyman** [comment]
Thanks!

**Pull request merged**
