### PR TITLE
CamelCase changes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by whyman** [comment]
Please ensure you also apply to all the ifdef variants

**Comment by neheb** [comment]
Not sure what you mean. This is mostly the web stuff.

**Comment by whyman** [comment]
Why did web not get updated?

For Cases where part is an acronym e.g. IO it should be in upper case. Eg FileIOHandler

**Comment by neheb** [comment]
Web is in the second commit.

**Comment by neheb** [comment]
Fixed FileIOHandler.

**Pull request merged**
