### PR TITLE
remove last std::list

### PR DESCRIPTION
**Pull request by neheb**
Removes compiler warnings on ARM regarding changed ABI.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
Do we care about those warnings? They are just warnings after all.

There is a reason to use list here. Can you tell me what it is?

**Comment by neheb** [comment]
Warnings are annoying :).

I don't know why list is used here.

Reading https://baptiste-wicht.com/posts/2012/12/cpp-benchmark-vector-list-deque.html indicates vector and deaue are better in most cases. Although these benchmarks use quite large values to show differences...

**Comment by whyman** [comment]
Did you test this?

**Comment by neheb** [comment]
I've done a basic test, yes. More accurately, my raw branch that includes this and other commits.

Adding and listening to music works just fine.

**Comment by whyman** [comment]
Does timer autoscan work? Multiple timer autoscans with different directories?

**Comment by neheb** [comment]
Tested, Works fine.

**Comment by whyman** [comment]
Just this patch, on its own

**Comment by neheb** [comment]
Same result.

std::list to std::deque just sacrifices removal (erase()) performance while everything else gets faster.

**Pull request merged**
