### PR TITLE
workaround is_regular_file for file > 2GB on 32bit systems

### PR DESCRIPTION
**Pull request by pamapa**
workaround for #737

### CODE REVIEW

**Comment by whyman** [comment]
Wow.

**Comment by neheb** [comment]
Does this error have anything to do with _FILE_OFFSET_BITS?

**Comment by whyman** [comment]
Probably this was fixed with GCC 9.3 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81091

**Comment by neheb** [comment]
Ah that is unfortunate.

**Comment by neheb** [comment]
Looks like this was backported to GCC 8.4.

I wonder if this was ever a problem with musl which always uses 64-bit APIs.

**Pull request merged**
