### PR TITLE
auto&& conversions

### PR DESCRIPTION
**Pull request by neheb**
Shorter.

### CODE REVIEW

**Comment by whyman** [comment]
Are `auto&&` const by default? Or does this just remove const-ness?

**Comment by neheb** [comment]
auto&& binds to anything, including const references. I do believe it evaluates to const ref first if possible.

**Comment by whyman** [comment]
I think I prefer to keep the explicit const, if only for the humans.

Otherwise looks fine to me.

**Comment by neheb** [comment]
I'll do some testing.

**Comment by neheb** [comment]
Actually now that I think about it, that wouldn't make sense. Adding const would prevent copy elision in certain situations.

**Comment by phi-whiterabbit** [comment]
If i may ask: What exactly is the point of such a change, except to obfuscate the code by hiding from the reader that all of these are references to a const object?

**Comment by phi-whiterabbit** [comment]
What i mean is: All the places where const auto & was used it was clear to the reader that it is a reference to a const object + having something different there like a reference to a mutable object would mit make sense.

Now i have to do the type deduction when reading.

**Comment by neheb** [comment]
Not all of them are references to a const object. Some of them are normal references.

**Pull request merged**
