### PR TITLE
remove std::stack

### PR DESCRIPTION
**Pull request by neheb**
No real benefit over vector. Small size reduction.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
Does using a stack for a stack not make sense?

**Comment by KarlStraussberger** [comment]
In my opinion `stack` semantics are clearer to understand

**Comment by neheb** [comment]
std::stack is implemented on top of vector. No real difference besides a size increase.

**Comment by neheb** [comment]
> In my opinion `stack` semantics are clearer to understand

I actually disagree. When I first converted to vector, I was getting runtime crashes. Turns out top needed to be replaced with back. It makes more sense to me this was by having back everywhere.

**Comment by KarlStraussberger** [comment]
It's used as a stack, it's called stack, so we keep it a stack

**Pull request closed without merging**
