### PR TITLE
Convert documentation to Sphinx & reStructuredText

### PR DESCRIPTION
**Pull request by elmodaddyb**
Provides documentation for system along with documentation for #245.

* Add screenshot capture spec for documentation
* Add image capture and manipulation
* Improve documentation including install, build, run, configuration and UI
* Add daemon documentation, improve document consistency
* Convert scripting documentation to RST
* Fix formatting with compile documentation
* Convert transcoding to restructured text, improve configuration maintainability
* Improve readability and cross-links
* Add links and improve spacing
* Improve formatting, use object domains for xml and js

### CODE REVIEW

**Comment by elmodaddyb** [comment]
This pull request contains documentation rewrite into **Sphinx** and **reStructuredText**.

### Refactored index page into following categories
   - Install Gerbera
   - Compile Gerbera
   - Run Gerbera
   - Gerbera Daemon
   - Configuration Overview
   - Configure Server
   - Configure Extended Options
   - Configure Content Import
   - Configure Online Content
   - Configure Transcoding
   - Gerbera UI
   - Scripting
   - Transcoding
   - Supported Devices

### Leverage reStructuredText
   - Include `genindex` items for index
   - Include various links between page content
   - Scripting uses `JavaScript` object domain for script content
  
### Removed outdated documentation
   - Removed YouTube support content
   - Removed **markdown** for daemon(systemd, launchd)
   - Removed `LyX` files
   - Removed `TXT` files generated from **lyx**

### Ported existing documentation to Sphinx
   - Scripting
   - Transcoding
   - Daemons

gerbera-docs

> Proof read the documentation a few times, but a few mistakes may be lingering.

**Comment by elmodaddyb** [comment]
@v00d00 

Please let me know how we can validate the `docs.gerbera.io` deployment.  I am interested to see the end result and make any adjustments.

Thanks,

Eamonn

**Comment by v00d00** [comment]
Now live on http://docs.gerbera.io/en/latest/

Looks great!

**Comment by astylos** [comment]
Massive improvement over the old doc - nice work!

**Comment by elmodaddyb** [comment]
**Woohooo!** Super stoked!  Thanks for merging the PR quickly!

**Pull request merged**
