### PR TITLE
use constexpr parameter for fmt::format

### PR DESCRIPTION
**Pull request by neheb**
Fixes compilation with fmt 8+ and c++20.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
No real idea how to handle the remaining ones:

https://github.com/neheb/gerbera/commit/3652e9f58f5091c248eae99b51ec4bf0aea712f0
https://github.com/neheb/gerbera/commit/b676e3500130f87eb1b7f757a104b6c1de51b177

**Comment by neheb** [comment]
any other issue?

**Comment by neheb** [comment]
Because fmt 8 uses consteval for the first parameter.

**Comment by whyman** [comment]
Right but with one arg you dont need to format anyway

**Comment by neheb** [comment]
It's equivalent to printf(foo) vs printf("%s", foo). Compiler complains about the former.

This pattern is already done elsewhere with fmt. Might as well maintain it.

**Comment by neheb** [comment]
Rebased.

**Pull request closed without merging**
