### PR TITLE
Add artist chronology container

### PR DESCRIPTION
**Pull request by gobater**
Add an artist chronology container (similar to album container, but sorted by date instead of name)

### CODE REVIEW

**Comment by gobater** [comment]
@KarlStraussberger , before I fix the tests, I would like to have your opinion on this...

**Comment by KarlStraussberger** [comment]
> @KarlStraussberger , before I fix the tests, I would like to have your opinion on this...

It's absolutely fine. Go ahead.

**Comment by gobater** [comment]
@KarlStraussberger , can you give me a hand fixing the broken test? It's passing in my machine :-( and I would expect it to pass in the CI since mock-config-minimal.xml seems correct to me.
Thanks

**Comment by KarlStraussberger** [comment]
The one missing is in `fixtures/mock-config-all.xml`

**Comment by KarlStraussberger** [comment]
There are several combinations of #defines that we test, hence all the xml-files

**Comment by KarlStraussberger** [comment]
Sorry it's `fixtures/mock-example-all.xml`

**Comment by gobater** [comment]
Oh! My bad! I didn't realize that my work was not in synch

**Pull request merged**
