### PR TITLE
fix matroska memory leaks

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
Can you describe the source of the leak and why this fixes it?

**Comment by neheb** [comment]
I cannot.

The leak was introduced with https://github.com/gerbera/gerbera/commit/947c72758635229ecfd1395c85934d38987acb06

building libebml as a meson subproject allowed Memory Sanitizer to see that the leak is in the parseMKV function. This is the only relevant change in that commit.

**Comment by KarlStraussberger** [comment]
From my point of view (and the logs in https://github.com/gerbera/gerbera/pull/2272#issuecomment-982195552) the leak is the call of `SkipData`

**Comment by neheb** [comment]
Right. And they go away with this PR. It's not fully clear to me why.

**Comment by neheb** [comment]
Current master:

```
=================================================================
==3376==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 340928 byte(s) in 5327 object(s) allocated from:
    #0 0x93ebd7 in operator new(unsigned long) (/home/mangix/devstuff/gerbera/addr/gerbera+0x93ebd7)
    #1 0x7f5a58819584  (/lib64/libebml.so.5+0x16584)

Direct leak of 3264 byte(s) in 1 object(s) allocated from:
    #0 0x90684f in __interceptor_realloc (/home/mangix/devstuff/gerbera/addr/gerbera+0x90684f)
    #1 0x7f5a580492ef  (/lib64/libixml.so.11+0x42ef)

Direct leak of 1512 byte(s) in 21 object(s) allocated from:
    #0 0x93ebd7 in operator new(unsigned long) (/home/mangix/devstuff/gerbera/addr/gerbera+0x93ebd7)
    #1 0x7f5a58814744  (/lib64/libebml.so.5+0x11744)

Direct leak of 17 byte(s) in 1 object(s) allocated from:
    #0 0x90684f in __interceptor_realloc (/home/mangix/devstuff/gerbera/addr/gerbera+0x90684f)
    #1 0x7f5a58062563  (/lib64/libupnp.so.17+0xe563)

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x9064a7 in malloc (/home/mangix/devstuff/gerbera/addr/gerbera+0x9064a7)
    #1 0x7f5a5807ac9d  (/lib64/libupnp.so.17+0x26c9d)

SUMMARY: AddressSanitizer: 345725 byte(s) leaked in 5351 allocation(s).
```

This PR fixes it.

**Comment by whyman** [comment]
Fixes in #2272

**Comment by neheb** [comment]
No there aren't. That commit is ineffective.

**Comment by whyman** [comment]
https://github.com/gerbera/gerbera/issues/2197#issuecomment-980101390 seems to indicate so to me

**Comment by neheb** [comment]
I can retest without this commit. But both valgrind and address sanitizer report this issue. The previous commit tried to but did not fix it.

**Comment by neheb** [comment]
yeah. without this commit:

```
==8086==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 44928 byte(s) in 702 object(s) allocated from:
    #0 0x932917 in operator new(unsigned long) (/home/mangix/devstuff/gerbera/addr/gerbera+0x932917)
    #1 0x7f68a984a584  (/lib64/libebml.so.5+0x16584)

Direct leak of 3264 byte(s) in 1 object(s) allocated from:
    #0 0x8fa58f in __interceptor_realloc (/home/mangix/devstuff/gerbera/addr/gerbera+0x8fa58f)
    #1 0x7f68a907e2ef  (/lib64/libixml.so.11+0x42ef)

Direct leak of 216 byte(s) in 3 object(s) allocated from:
    #0 0x932917 in operator new(unsigned long) (/home/mangix/devstuff/gerbera/addr/gerbera+0x932917)
    #1 0x7f68a9845744  (/lib64/libebml.so.5+0x11744)

Direct leak of 17 byte(s) in 1 object(s) allocated from:
    #0 0x8fa58f in __interceptor_realloc (/home/mangix/devstuff/gerbera/addr/gerbera+0x8fa58f)
    #1 0x7f68a9095563  (/lib64/libupnp.so.17+0xe563)

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x8fa1e7 in malloc (/home/mangix/devstuff/gerbera/addr/gerbera+0x8fa1e7)
    #1 0x7f68a90adc9d  (/lib64/libupnp.so.17+0x26c9d)

SUMMARY: AddressSanitizer: 48429 byte(s) leaked in 708 allocation(s).
```

**Comment by neheb** [comment]
valgrind output is even worse: https://gist.github.com/neheb/a448a88f55e0ebd13981ef6c5d6ed9f0

It points to a problem in taglib.

**Comment by whyman** [comment]
Looks more like your valigrind is not understanding ` __wmemcmp_avx2_movbe`

I bet if you recompiled taglib in debug optimisation level it would go away.

**Comment by whyman** [comment]
Is it possible to get the source locations out of LeakSanitizer?

**Comment by neheb** [comment]
Yeah I can build as a subproject.

**Pull request closed without merging**
