### PR TITLE
Repeatable Sphinx build for documentation

### PR DESCRIPTION
**Pull request by elmodaddyb**
* Support python virtualenv for documentation build
* Check for virtualenv to avoid failures

### CODE REVIEW

**Comment by elmodaddyb** [comment]
This PR improves the sphinx build script to use a insulated `virtualenv` with python.  This is in preparation for the future features like:

1. Publish **docs** when gerbera builds in Travis CI.
2. Automate build of **docs** for Gerbera UI

I was going to cleanup the `/doc` directory but was not sure what is outdated? 

@v00d00 can you help with document status...is only `index.rst` valid?

I tested the script on the following systems **successfully**

* macOS High Sierra
* Fedora 27

**Comment by elmodaddyb** [comment]
Improved iteration speed when developing locally by introducing a `--clobber` option which avoids removing/recreating a new `virtualenv` environment on every run.

Document building is very much a back/forth activity, so this helps tremendously.

**Comment by v00d00** [comment]
Most of the readme.lyx is still correct, same for scripting.lyx and transcoding.lyx but they all need converting to rst and sphinx-ifying, then they can get removed.

**Comment by elmodaddyb** [comment]
@v00d00 - thanks for the reply.  I will iterate over those documents(`readme`,`scripting`,`transcoding`), using the script..and see how it goes.

You can merge this PR if you prefer, or wait for the documents to be converted and included with this PR.  Likely I will work on the document conversion this weekend.

> I also have a full UI document nearly complete.

**Pull request merged**
