### PR TITLE
don't allocate empty pugixml pointers

### PR DESCRIPTION
**Pull request by neheb**
Fixes multiple fanalyzer warnings, even unrelated ones.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Setting as draft, Last time I tried this it failed with Ubuntu.

### CODE REVIEW

**Comment by neheb** [comment]
Hmm guess not.

**Comment by whyman** [comment]
What are the warnings? The code before is fine.

**Comment by neheb** [comment]
nullptr allocations. Specifically, it complains that the this pointer of xml_document is null in make_unique.

**Comment by whyman** [comment]
That is false though as it constructs a document and wraps it in a pointer.

**Comment by neheb** [comment]
Error from -fanalyzer:

```
[1/144] Building CXX object CMakeFiles/libgerbera.dir/src/action_request.cc.o
In function ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = pugi::xml_document; _Args = {}]’:
cc1plus: warning: use of possibly-NULL ‘operator new(208)’ where non-null expected [CWE-690] [-Wanalyzer-possible-null-argument]
  ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = pugi::xml_document; _Args = {}]’: event 1
    |
    |/usr/include/c++/11/bits/unique_ptr.h:962:30:
    |  962 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
    |      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |                              |
    |      |                              (1) this call could return NULL
    |
  ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = pugi::xml_document; _Args = {}]’: event 2
    |
    |cc1plus:
    | (2): argument 'this' (‘operator new(208)’) from (1) could be NULL where non-null expected
    |
In file included from src/action_request.h:37,
                 from src/action_request.cc:32:
/usr/include/pugixml.hpp:1039:17: note: argument 'this' of ‘pugi::xml_document::xml_document()’ must be non-null
 1039 |                 xml_document();
      |                 ^~~~~~~~~~~~
[2/144] Building CXX object CMakeFiles/libgerbera.dir/src/content/autoscan.cc.o
[3/144] Building CXX object CMakeFiles/libgerbera.dir/src/content/autoscan_list.cc.o
[4/144] Building CXX object CMakeFiles/libgerbera.dir/src/config/dynamic_content.cc.o
[5/144] Building CXX object CMakeFiles/libgerbera.dir/src/config/directory_tweak.cc.o
[6/144] Building CXX object CMakeFiles/libgerbera.dir/src/content/layout/js_layout.cc.o
[7/144] Building CXX object CMakeFiles/libgerbera.dir/src/content/layout/layout.cc.o
[8/144] Building CXX object CMakeFiles/libgerbera.dir/src/config/client_config.cc.o
[9/144] Building CXX object CMakeFiles/libgerbera.dir/src/content/onlineservice/atrailers_service.cc.o
[10/144] Building CXX object CMakeFiles/libgerbera.dir/src/content/onlineservice/lastfm_scrobbler.cc.o
[11/144] Building CXX object CMakeFiles/libgerbera.dir/src/content/onlineservice/curl_online_service.cc.o
In function ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = pugi::xml_document; _Args = {}]’:
cc1plus: warning: use of possibly-NULL ‘operator new(208)’ where non-null expected [CWE-690] [-Wanalyzer-possible-null-argument]
  ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = pugi::xml_document; _Args = {}]’: event 1
    |
    |/usr/include/c++/11/bits/unique_ptr.h:962:30:
    |  962 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
    |      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |                              |
    |      |                              (1) this call could return NULL
    |
  ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = pugi::xml_document; _Args = {}]’: event 2
    |
    |cc1plus:
    | (2): argument 'this' (‘operator new(208)’) from (1) could be NULL where non-null expected
    |
In file included from src/content/onlineservice/curl_online_service.h:34,
                 from src/content/onlineservice/curl_online_service.cc:27:
/usr/include/pugixml.hpp:1039:17: note: argument 'this' of ‘pugi::xml_document::xml_document()’ must be non-null
 1039 |                 xml_document();
      |                 ^~~~~~~~~~~~
[12/144] Building CXX object CMakeFiles/libgerbera.dir/src/content/onlineservice/online_service.cc.o
```

**Comment by whyman** [comment]
Yeah that is `-fanalyzer` just being stupid and not handling smart pointers.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94355

**Pull request closed without merging**
