### PR TITLE
use clock_gettime instead of timespec_get

### PR DESCRIPTION
**Pull request by neheb**
The latter is not available in Haiku for some reason.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
This is quite the hack. I wonder if all this code can be converted to use std::chrono.

**Comment by whyman** [comment]
I think a conversion to std::chrono would be nicer too.

**Comment by extrowerk** [comment]
It builds fine on Haiku.

**Comment by neheb** [comment]
macos failure is a false positive I think.

Anyway, using clock_gettime is not really portable. It happens to work on Linux and BSDs, but will fail on Windows and old macOS.

**Comment by extrowerk** [comment]
Still builds fine

**Review by whyman — COMMENTED** [review]
Shouldnt `getTimespecNow` get removed entirely thanks to chrono?

**Comment by neheb** [comment]
Patches welcome :). I wasn't able to figure it out fully.

**Pull request merged**
