### PR TITLE
Docker.md: add docker-compose instructions

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by hmoffatt** [comment]
The docker-compose instructions refer to a named volume called gebera-config, which is not defined in the instructions.

**Comment by neheb** [comment]
doesn't it get automatically created?

**Comment by hmoffatt** [comment]
No:
```
ERROR: Named volume "gerbera-config:/var/run/gerbera:rw" is used in service "gerbera" but no declaration was found in the volumes section.
```

**Comment by hmoffatt** [comment]
You need to declare a volume with:

```
volumes:
  gerbera-config: {}

```

**Pull request merged**
