### PR TITLE
This and that

### PR DESCRIPTION
**Pull request by KarlStraussberger**
May even solve:
#2630
#2628

### CODE REVIEW

**Comment by paolostivanin** [comment]
Hello! I've built a version with this patch applied, but the issue is still there:

```
[  647s]   9/146 Test  #12: ResolutionTest.parse .......................................................................***Failed    0.02 sec
[  647s] Note: Google Test filter = ResolutionTest.parse
[  647s] [==========] Running 1 test from 1 test suite.
[  647s] [----------] Global test environment set-up.
[  647s] [----------] 1 test from ResolutionTest
[  647s] [ RUN      ] ResolutionTest.parse
[  647s] [2022-05-17 18:39:17.140] [error] [tools.cc:124] stoul (input 54589448448485)
[  647s] unknown file: Failure
[  647s] C++ exception with description "[/home/abuild/rpmbuild/BUILD/gerbera-1.11.0/src/metadata/resolution.cc:45] Resolution::Resolution(const std::string&) Error: Failed to parse '122586668x54589448448485' to valid resolution" thrown in the test body.
[  647s] [  FAILED  ] ResolutionTest.parse (0 ms)
[  647s] [----------] 1 test from ResolutionTest (0 ms total)
```

**Comment by KarlStraussberger** [comment]
> Hello! I tried to build a version with this patch applied, but the issue is still there:
> 
> ```
> [  647s]   9/146 Test  #12: ResolutionTest.parse .......................................................................***Failed    0.02 sec
> [  647s] Note: Google Test filter = ResolutionTest.parse
> [  647s] [==========] Running 1 test from 1 test suite.
> [  647s] [----------] Global test environment set-up.
> [  647s] [----------] 1 test from ResolutionTest
> [  647s] [ RUN      ] ResolutionTest.parse
> [  647s] [2022-05-17 18:39:17.140] [error] [tools.cc:124] stoul (input 54589448448485)
> [  647s] unknown file: Failure
> [  647s] C++ exception with description "[/home/abuild/rpmbuild/BUILD/gerbera-1.11.0/src/metadata/resolution.cc:45] Resolution::Resolution(const std::string&) Error: Failed to parse '122586668x54589448448485' to valid resolution" thrown in the test body.
> [  647s] [  FAILED  ] ResolutionTest.parse (0 ms)
> [  647s] [----------] 1 test from ResolutionTest (0 ms total)
> ```

I updated the code to get more details on the issue. It would be pleasant of you to rerun your test.

**Comment by KarlStraussberger** [comment]
> > Hello! I tried to build a version with this patch applied, but the issue is still there:
> > ```
> > [  647s]   9/146 Test  #12: ResolutionTest.parse .......................................................................***Failed    0.02 sec
> > [  647s] Note: Google Test filter = ResolutionTest.parse
> > [  647s] [==========] Running 1 test from 1 test suite.
> > [  647s] [----------] Global test environment set-up.
> > [  647s] [----------] 1 test from ResolutionTest
> > [  647s] [ RUN      ] ResolutionTest.parse
> > [  647s] [2022-05-17 18:39:17.140] [error] [tools.cc:124] stoul (input 54589448448485)
> > [  647s] unknown file: Failure
> > [  647s] C++ exception with description "[/home/abuild/rpmbuild/BUILD/gerbera-1.11.0/src/metadata/resolution.cc:45] Resolution::Resolution(const std::string&) Error: Failed to parse '122586668x54589448448485' to valid resolution" thrown in the test body.
> > [  647s] [  FAILED  ] ResolutionTest.parse (0 ms)
> > [  647s] [----------] 1 test from ResolutionTest (0 ms total)
> > ```
> 
> I updated the code to get more details on the issue. It would be pleasant of you to rerun your test.

@paolostivanin forgot to reference you in the response :-(

**Comment by paolostivanin** [comment]
Result with the updated patch:

```
[  268s] 12: Note: Google Test filter = ResolutionTest.parse
[  268s] 12: [==========] Running 1 test from 1 test suite.
[  268s] 12: [----------] Global test environment set-up.
[  268s] 12: [----------] 1 test from ResolutionTest
[  268s] 12: [ RUN      ] ResolutionTest.parse
[  268s] 12: [2022-05-18 08:44:33.050] [error] [tools.cc:127] oor stoul (input 54589448448485)
[  268s] 12: unknown file: Failure
[  268s] 12: C++ exception with description "[/home/abuild/rpmbuild/BUILD/gerbera-1.11.0/src/metadata/resolution.cc:45] Resolution::Resolution(const std::string&) Error: Failed to parse '122586668x54589448448485' to valid resolution" thrown in the test body.
[  268s] 12: [  FAILED  ] ResolutionTest.parse (0 ms)
[  268s] 12: [----------] 1 test from ResolutionTest (0 ms total)
[  268s] 12: 
[  268s] 12: [----------] Global test environment tear-down
[  268s] 12: [==========] 1 test from 1 test suite ran. (0 ms total)
[  268s] 12: [  PASSED  ] 0 tests.
[  268s] 12: [  FAILED  ] 1 test, listed below:
[  268s] 12: [  FAILED  ] ResolutionTest.parse
[  268s] 12: 
[  268s] 12:  1 FAILED TEST
[  268s] 6: [       OK ] ConfigGeneratorTest.GeneratesExtendedRuntimeXmlWithFFMPEG (19 ms)
[  268s] 6: [----------] 1 test from ConfigGeneratorTest (19 ms total)
```

**Pull request merged**
