### PR TITLE
Switch from hexdump to xxd

### PR DESCRIPTION
**Pull request by whyman**
Hexdump is apparently not available on OpenWrt

Closes: #1142

### CODE REVIEW

**Comment by whyman** [comment]
Hah, of course it doesnt work on busybox :/

**Comment by neheb** [comment]
either I'm on crack or OpenWrt's busybox includes hexdump.

**Comment by neheb** [comment]
Yeah forget about it. hexdump is part of util-linux which is included in every linux installation.

I think the packages in OpenWrt that use xxd need to be fixed.

**Comment by whyman** [comment]
Okay, I will update the patch to check for hexdump as originally planned.

Is there any way we can include OpenWrt in our CI? Docker builds or something?

**Comment by neheb** [comment]
Good question. There is https://github.com/openwrt/docker but that's for the entire tree.

ping @aparcar

**Comment by aparcar** [comment]
You can use a [GitHub action](https://github.com/openwrt/gh-action-sdk) to build the package from a custom feed or use the `openwrtorg/sdk` container directly.

**Pull request closed without merging**
