### PR TITLE
Make CFG_IMPORT_SCRIPTING_IMPORT_GENRE_MAP available

### PR DESCRIPTION
**Pull request by KarlStraussberger**
fixes compilation error without JS

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
@whyman We should have a test build with JS disabled 😄

**Comment by whyman** [comment]
> @whyman We should have a test build with JS disabled smile

Definitely!

**Comment by neheb** [comment]
Seems incomplete:

```
C:/msys64/home/Mangix/devstuff/gerbera/src/config/config_manager.cc:811:48: error: use of undeclared identifier 'CFG_IMPORT_SCRIPTING_IMPORT_SCRIPT_OPTIONS'; did you mean 'CFG_IMPORT_SCRIPTING_IMPORT_GENRE_MAP'?
    { ATTR_IMPORT_LAYOUT_SCRIPT_OPTION_NAME, { CFG_IMPORT_SCRIPTING_IMPORT_SCRIPT_OPTIONS } },
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                               CFG_IMPORT_SCRIPTING_IMPORT_GENRE_MAP
C:/msys64/home/Mangix/devstuff/gerbera/src\config/config.h:134:5: note: 'CFG_IMPORT_SCRIPTING_IMPORT_GENRE_MAP' declared here
    CFG_IMPORT_SCRIPTING_IMPORT_GENRE_MAP,
    ^
C:/msys64/home/Mangix/devstuff/gerbera/src/config/config_manager.cc:812:49: error: use of undeclared identifier 'CFG_IMPORT_SCRIPTING_IMPORT_SCRIPT_OPTIONS'; did you mean 'CFG_IMPORT_SCRIPTING_IMPORT_GENRE_MAP'?
    { ATTR_IMPORT_LAYOUT_SCRIPT_OPTION_VALUE, { CFG_IMPORT_SCRIPTING_IMPORT_SCRIPT_OPTIONS } },
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                CFG_IMPORT_SCRIPTING_IMPORT_GENRE_MAP
C:/msys64/home/Mangix/devstuff/gerbera/src\config/config.h:134:5: note: 'CFG_IMPORT_SCRIPTING_IMPORT_GENRE_MAP' declared here
    CFG_IMPORT_SCRIPTING_IMPORT_GENRE_MAP,

```

**Comment by KarlStraussberger** [comment]
That's another one. Thanks.

**Pull request merged**
