### PR TITLE
move UpdateManager, TaskProcessor, Runtime and LastFm into ContentManager

### PR DESCRIPTION
**Pull request by pamapa**

### CODE REVIEW

**Comment by pamapa** [comment]
As next i plan to move directly content manager related stuff into new subdir `content`:
- DIR `content`
  - DIR layout ...
  - DIR onlineservice ...
  - DIR scripting ...
  - autoscan*.*
  - content_manager.*
  - update_manager.*

This should make the code more readable...

**Comment by whyman** [comment]
This commit does the opposite of what the message says :thinking:

**Comment by pamapa** [comment]
ups, thanks for the catch! Fixed now

**Comment by pamapa** [comment]
ready to be merged

**Review by whyman — APPROVED** [review]

**Comment by KarlStraussberger** [comment]
With the previous commit I got a #1098 regression. Can you check for that.

**Comment by pamapa** [comment]
@KarlStraussberger thanks for reporting, i have fixed the crash in a seperate merge request, see #1111

**Pull request merged**
