### PR TITLE
Free XMP namespaces

### LINKED ISSUE #2264: exiv2 memory leak
```
  31 Direct leak of 65 byte(s) in 2 object(s) allocated from:
  32     #0 0x9094e7 in malloc (/home/mangix/devstuff/gerbera/addr/gerbera+0x9094e7)
  33     #1 0x7f510aa121ae in Exiv2::XmpProperties::registerNs(std::__cxx11::basic_string<char, std::char_traits<char>     , std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >      const&) (/lib64/libexiv2.so.27+0x10d1ae)
  34 
  35 Direct leak of 13 byte(s) in 2 object(s) allocated from:
  36     #0 0x9094e7 in malloc (/home/mangix/devstuff/gerbera/addr/gerbera+0x9094e7)
  37     #1 0x7f510aa121d0 in Exiv2::XmpProperties::registerNs(std::__cxx11::basic_string<char, std::char_traits<char>     , std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >      const&) (/lib64/libexiv2.so.27+0x10d1d0)
```

not a large amount probably because I don't have many pictures with XMP data...

### PR DESCRIPTION
**Pull request by KarlStraussberger**
fixes #2264

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
@neheb Can you please confirm-

**Comment by whyman** [comment]
Should probably do it after the catch?

**Comment by KarlStraussberger** [comment]
Good point

**Comment by neheb** [comment]
Seems to fix it.

**Pull request merged**
