### PR TITLE
use auto instead of const char*

### PR DESCRIPTION
**Pull request by neheb**
Too much const otherwise.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
I like the types. auto makes you think more 🙃

**Comment by KarlStraussberger** [comment]
Me too, as long as isn't obvious - like with the char here. Now you can even read it as string.

**Comment by whyman** [comment]
Yeah nothing against this change particularly, just as a decidedly part time C++ user it adds to the complexity

**Comment by neheb** [comment]
It's perfectly fine for simple types and right side type assignment. Also if you don't care about the type of something.

But otherwise yes.

**Comment by KarlStraussberger** [comment]
> Yeah nothing against this change particularly, just as a decidedly part time C++ user it adds to the complexity
> 
> Same with the automatic move magic. C++ is complicated 😅😄😬

That's what keeps our little grey things below the hair alive

**Pull request merged**
