### PR TITLE
Optimize album art

### PR DESCRIPTION
**Pull request by whorfin**
I've tried a number of strategies, which often end up being undone by the SQL scheduler.
Without changing the database schema [additional complicated functional indices] this is the best I've got at the moment.
...I made a mistake at some point and had my database in a non-default state; this works as long as you've not messed around with PRAGMA

Perhaps it will help with #138 

Cheers

### CODE REVIEW

**Comment by v00d00** [comment]
Which DBs did you test with?

**Comment by whorfin** [comment]
Only SQLite.
_should_ work fine with MySQL but I didn’t test

**Comment by whorfin** [comment]
A note on these two additional commits:
I noticed that not all DLNA clients behave the same, even same client on different platform [ios vs android]
I found that 8player was working fine but foobar2000 was timing out.
These two changes further improved performance significantly.
They again _should_ work on MySQL

An additional table change
CREATE INDEX mt_cds_object_parent_type ON mt_cds_object(parent_id,object_type);
would speed some queries by as much as 3x; yes these fields are present in an existing index, but the scheduler is affected in a way that can matter.

But we can avoid a database change by leaving this alone [though CREATE INDEX ... IF NOT EXIST would also work easily]; this requested PULL works well and is defensible - there's no particular reason to prefer alphabetically first cover filename match when there are several.

**Comment by whorfin** [comment]
this last bit helps some DLNA clients avoid a timeout
it makes eg 8player really really responsive at metadata-driven [ie "Genres" or "Albums"] lists

**Comment by v00d00** [comment]
Lets merge this, and hopefully we get some feedback on MySQL.

**Pull request merged**
