### PR TITLE
Instructions to build gerbera on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by Juergen-W**
After spending a couple of hours i succeed to build gerbera on Ubuntu 18.04 LTS. I'm not sure if every package is really needed (like g++-8). Compiling with g++-8 runs into errors, clang++ works fine,

### CODE REVIEW

**Comment by whyman** [comment]
Looks but you can you whittle it down to the one compiler? Probably the clang9?

**Comment by Juergen-W** [comment]
I just tried my instructions on a fresh installed ubuntu 18.04 without gcc-8 and g++-8. 
cmake stops with an error:
CMake Error at cmake/FindFilesystem.cmake:227 (message):
  Cannot Compile simple program using std::filesystem
Call Stack (most recent call first):
  CMakeLists.txt:272 (find_package)

After installing g++-8 everything is ok. But if you compile with g++ and not with clang++ then an error occurs: when "building CXX object. CMakeFiles/libgerbera.dir/src/metadata/ffmpeg_handler.cc.o". Yes, it's confusing (for me). I think i read something about a bug in g++-8.

**Comment by whyman** [comment]
I guess instead of `g++-8` you many need `libstdc++`?

**Comment by Juergen-W** [comment]
Do you know how to send the compiler option "-L /usr/lib/gcc/x86_64-linux-gnu/8" within cmake? Maybe then it works...

**Comment by whyman** [comment]
Odd, can you post your build log?

**Comment by Juergen-W** [comment]
Here is the output of cmake (without g++-8 but with libsdtc++-8-package):
`LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/8:$LD_LIBRARY_PATH cmake -DCMAKE_LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/8 -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=1 ../gerbera
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include optional
-- Looking for C++ include optional - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - found
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - not found
CMake Error at cmake/FindFilesystem.cmake:227 (message):
  Cannot Compile simple program using std::filesystem
Call Stack (most recent call first):
  CMakeLists.txt:272 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/wutschi/build/CMakeFiles/CMakeOutput.log".
See also "/home/wutschi/build/CMakeFiles/CMakeError.log".
`
I think the reason is that the compiler/linker takes the first version of sdtc++ which is v7. "find /usr/lib -name libstc++" prints this:
/usr/lib/gcc/x86_64-linux-gnu/8/libstdc++.so
/usr/lib/gcc/x86_64-linux-gnu/8/libstdc++.a
/usr/lib/gcc/x86_64-linux-gnu/8/libstdc++fs.a
/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.so
/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++.a
/usr/lib/gcc/x86_64-linux-gnu/7/libstdc++fs.a

Result of "sudo apt remove libstdc++-7-dev" is that build-essential clang clang-6.0 clang-9 g++ g++-7 will also be removed. So "sudo apt install clang-9" and running
cmake -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=1 -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMILER=/usr/bin/clang++ ../gerbera
is ok, "make" compiles every source file but errors occur while linking:
CMakeFiles/gerbera.dir/src/main.cc.o: In function `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::format_to<fmt::v6::basic_string_view<char>, char const (&) [10], char const (&) [19], 250ul, char>(fmt::v6::basic_memory_buffer<char, 250ul, std::allocator<char> >&, fmt::v6::basic_string_view<char> const&, char const (&) [10], char const (&) [19])':
main.cc:(.text._ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRA10_KcRA19_S4_ELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESD_E8iteratorERNS0_19basic_memory_bufferISD_XT1_ESaISD_EEERKT_DpOT0_[_ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRA10_KcRA19_S4_ELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESD_E8iteratorERNS0_19basic_memory_bufferISD_XT1_ESaISD_EEERKT_DpOT0_]+0x8d): undefined reference to `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::internal::vformat_to<char>(fmt::v6::internal::buffer<char>&, fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<fmt::v6::type_identity<char>::type> >, fmt::v6::type_identity<char>::type> >)'
CMakeFiles/gerbera.dir/src/main.cc.o: In function `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::format_to<fmt::v6::basic_string_view<char>, char const* const&, 250ul, char>(fmt::v6::basic_memory_buffer<char, 250ul, std::allocator<char> >&, fmt::v6::basic_string_view<char> const&, char const* const&)':
main.cc:(.text._ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRKPKcELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESC_E8iteratorERNS0_19basic_memory_bufferISC_XT1_ESaISC_EEERKT_DpOT0_[_ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRKPKcELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESC_E8iteratorERNS0_19basic_memory_bufferISC_XT1_ESaISC_EEERKT_DpOT0_]+0x80): undefined reference to `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::internal::vformat_to<char>(fmt::v6::internal::buffer<char>&, fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<fmt::v6::type_identity<char>::type> >, fmt::v6::type_identity<char>::type> >)'
CMakeFiles/gerbera.dir/src/main.cc.o: In function `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::format_to<fmt::v6::basic_string_view<char>, char const* const&, char const* const&, 250ul, char>(fmt::v6::basic_memory_buffer<char, 250ul, std::allocator<char> >&, fmt::v6::basic_string_view<char> const&, char const* const&, char const* const&)':
main.cc:(.text._ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRKPKcS7_ELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESC_E8iteratorERNS0_19basic_memory_bufferISC_XT1_ESaISC_EEERKT_DpOT0_[_ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRKPKcS7_ELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESC_E8iteratorERNS0_19basic_memory_bufferISC_XT1_ESaISC_EEERKT_DpOT0_]+0x8d): undefined reference to `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::internal::vformat_to<char>(fmt::v6::internal::buffer<char>&, fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<fmt::v6::type_identity<char>::type> >, fmt::v6::type_identity<char>::type> >)'
CMakeFiles/gerbera.dir/src/main.cc.o: In function `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::format_to<fmt::v6::basic_string_view<char>, int const&, 250ul, char>(fmt::v6::basic_memory_buffer<char, 250ul, std::allocator<char> >&, fmt::v6::basic_string_view<char> const&, int const&)':
main.cc:(.text._ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRKiELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESA_E8iteratorERNS0_19basic_memory_bufferISA_XT1_ESaISA_EEERKT_DpOT0_[_ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRKiELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESA_E8iteratorERNS0_19basic_memory_bufferISA_XT1_ESaISA_EEERKT_DpOT0_]+0x80): undefined reference to `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::internal::vformat_to<char>(fmt::v6::internal::buffer<char>&, fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<fmt::v6::type_identity<char>::type> >, fmt::v6::type_identity<char>::type> >)'
liblibgerbera.a(config_manager.cc.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v6::internal::vformat<char>(fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<fmt::v6::type_identity<char>::type> >, fmt::v6::type_identity<char>::type> >)':
config_manager.cc:(.text._ZN3fmt2v68internal7vformatIcEENSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEENS0_17basic_string_viewIS5_EENS0_17basic_format_argsINS0_20basic_format_contextISt20back_insert_iteratorINS1_6bufferINS0_13type_identityIS5_E4typeEEEESI_EEEE[_ZN3fmt2v68internal7vformatIcEENSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEENS0_17basic_string_viewIS5_EENS0_17basic_format_argsINS0_20basic_format_contextISt20back_insert_iteratorINS1_6bufferINS0_13type_identityIS5_E4typeEEEESI_EEEE]+0xa4): undefined reference to `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::internal::vformat_to<char>(fmt::v6::internal::buffer<char>&, fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<fmt::v6::type_identity<char>::type> >, fmt::v6::type_identity<char>::type> >)'
liblibgerbera.a(config_manager.cc.o):config_manager.cc:(.text._ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESG_E8iteratorERNS0_19basic_memory_bufferISG_XT1_ESaISG_EEERKT_DpOT0_[_ZN3fmt2v69format_toINS0_17basic_string_viewIcEEJRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEELm250EcEENS0_20basic_format_contextISt20back_insert_iteratorINS0_8internal6bufferIT2_EEESG_E8iteratorERNS0_19basic_memory_bufferISG_XT1_ESaISG_EEERKT_DpOT0_]+0x80): more undefined references to `fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::internal::vformat_to<char>(fmt::v6::internal::buffer<char>&, fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<fmt::v6::type_identity<char>::type> >, fmt::v6::type_identity<char>::type> >)' follow

I know these error from my attempts before...

**Comment by whyman** [comment]
Thanks! Im going to merge this, we can tidy it up as needed.

**Pull request merged**
