### PR TITLE
switch to C++ ffmpegthumbnailer API

### PR DESCRIPTION
**Pull request by neheb**
Small simplification.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
Nice! Does it work?

**Comment by KarlStraussberger** [comment]
no problems so far.

**Comment by neheb** [comment]
> Nice! Does it work?

I haven't done through testing but it should work. The names are similar anyway. Except for the overlay strip thing. I had to look at the code to see how it was done.

**Comment by neheb** [comment]
I wonder if that lock is needed anymore. The surrounding code looks like it could be cleaned up further. It looks like it's made to deal with C stuff.

**Pull request merged**
