### PR TITLE
use make_pair in std::array

### PR DESCRIPTION
**Pull request by neheb**
Allows using CTAD and getting rid of extra {}.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

CTAD is a good idea. The first entry explains why. The array was updated at some point but the size was not. That can cause issues when accessing entries outside of the array.

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
I prefer having the enum types in array declaration. Otherwise you always have to look up the exact types in order to understand the code. In cases when you add enum props you cannot grep for the type to check the usages.

**Comment by neheb** [comment]
I don't agree but added anyway.

**Comment by neheb** [comment]
added some extra ones.

**Comment by neheb** [comment]
switched to std::pair. It's the exact same as make_pair turns out.

**Pull request merged**
