### PR TITLE
Some conan fixes and GitHub actions

### PR DESCRIPTION
**Pull request by ytimenkov**
Example: https://github.com/ytimenkov/gerbera/actions/runs/144089972

### CODE REVIEW

**Comment by ytimenkov** [comment]
1. Problem (?) with current setup of GitHub actions is that they're triggered also on forks.
2. Travis can be removed (if it's the plan).
3. Proposed GitHub actions don't use any docker image and run natively on VM. Thankfully everything is set up there. However build times are slightly longer compared to Travis because most of C++ packages need to be rebuilt (since Gerbera uses C++17 and default binary packages on Conan-Center are for C++14). I plan to experiment with cache.

**Comment by whyman** [comment]
Looks sensible, I wouldnt mind keeping the alpine build for PRs too, even if its a minor duplication, checks the non Conan build is OK.

**Comment by ytimenkov** [comment]
> Looks sensible, I wouldnt mind keeping the alpine build for PRs too, even if its a minor duplication, checks the non Conan build is OK.

Alpine build or docker? I mean like it was in Travis: commands ran inside prebuilt container or line it's now: do everything in `docker build`?

**Comment by whyman** [comment]
Sorry I meant the docker(alpine) image build.

I dont really care about the VM vs docker for the conan builds. Whatever is easier. We only went with Docker on travis as their VM images are ancient.

**Comment by goettl79** [comment]
Hi, this actually prevented the automatic v1.6.0 release. I'd remove the limit on the master branch or just take branches/tags that start with v.

**Pull request merged**
