### PR TITLE
replace queue with vector

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
For what reason?

**Comment by neheb** [comment]
The former is implemented in terms of the latter. No real difference besides a size increase.

**Comment by whyman** [comment]
For humans its clearer to use a `queue` when you are dealing with a queue.

**Comment by KarlStraussberger** [comment]
It's used as a queue so it should be a queue.

**Pull request closed without merging**
