### PR TITLE
Add audio/flac to relevant places

### PR DESCRIPTION
**Pull request by chiraag-nataraj**
I think this should work? `gerbera --create-config` seems to show the right value. Fix for #296

### CODE REVIEW

**Comment by elmodaddyb** [comment]
Can you update the unit test fixtures to match XML?

**Comment by elmodaddyb** [comment]
Looks good.  Any thoughts on the testing approach.  Its been in place for a bit and wondering if you found it easy or troubling to know where to update?

> Any thoughts?

**Comment by chiraag-nataraj** [comment]
> Looks good. Any thoughts on the testing approach. Its been in place for a bit and wondering if you found it easy or troubling to know where to update?

The tests weren't too bad to update. The only reason I needed a second commit was that for some reason a tab was inserted in one of the tests instead of a space (which I caught only when the test failed).

**Comment by v00d00** [comment]
Looks good, thanks!

**Pull request merged**
