### PR TITLE
make bultinClientInfo constexpr

### PR DESCRIPTION
**Pull request by neheb**
Avoids destructor nastiness.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
GCC's libstdc++ is fine. LLVM's libc++ is not. Hmmmmm.

**Comment by neheb** [comment]
As far as I can tell, libc++ has problems assigning to an std::string_view whereas libstdc++ does not. Needs a closer look.

**Comment by neheb** [comment]
Hmm OK. Maybe it's a problem with the types having to match.

As far as the js issue, that seems to be introduced with https://github.com/gerbera/gerbera/commit/89d022b2251d59214b724fc6f6cea7fd2130c76c .

I have absolutely no idea why...

**Comment by neheb** [comment]
meh. heisenbug.

**Comment by KarlStraussberger** [comment]
> 
> Hmm OK. Maybe it's a problem with the types having to match.
> 
> As far as the js issue
> 
> I have absolutely no idea why...

JS issue is around for a year already. I think it is just a problem of timers passing in low priority containers. After kicking the test once again it runs smoothly.

**Comment by KarlStraussberger** [comment]
I'll have to revert most of this change, because it break client detection.

`string_view` refers to the stored pointer even if the target is gone already (e.g. after reading `config.xml`)

**Pull request merged**
