### PR TITLE
Config: Make UDN mandatory

### LINKED ISSUE #2891: Gerbera 1.12 not showing up on the network
Hi Guys, I don't really have any ideas how to troubleshoot or find out what is the problem. I updated  to Kubuntu 23.10 - it comes with gerbera 1.12 (instead of 1.1 in the previous distro versions).

The previous versions worked normally. But the 1.12 does not show up on the TV, nor in the `gupnp-universal-cp` tool.

If I run the previous version (1.1) in VirtualBox, it shows up normally on all other devices on the network.

Please help me with troubleshooting

### LINKED ISSUE #3200: Warn user if `udn` is unset
I have noticed Gerbera (probably I should say `libupnp`) does not send SSDP notifications if `udn` value in unset (eg `<udn/>`) in `config.xml`. Maybe it would make sense to detect the issue and display a warning on start?

### PR DESCRIPTION
**Pull request by KarlStraussberger**
closes #3200
closes #2891

### CODE REVIEW

**Comment by whyman** [comment]
The issue here is that if distros ship a usb, you end up with possible duplicate udn on that same network.

Could we just generate a udn if it's not present?

**Comment by KarlStraussberger** [comment]
> The issue here is that if distros ship a UDN in their default config, you end up with possible duplicate udn on that same network.
> 
> Could we just generate a udn if it's not present?

It has to be the same each time otherwise some clients will keep duplicate entries that are not browsable. I'm thinking of generating one and storing it in the database - once it's up. Config check takes place before database connection is established.

**Comment by whyman** [comment]
> It has to be the same each time otherwise some clients will keep duplicate entries that are not browsable. I'm thinking of generating one and storing it in the database - once it's up. Config check takes place before database connection is established.

Yeah good idea.

**Comment by KarlStraussberger** [comment]
Added the 3 lines in #3209

**Pull request merged**
