### PR TITLE
Improve systemd install instructions, fixes #162

### LINKED ISSUE #162: Unable to launch gerbera via systemd
Hi there,

first of all I'd like to thank you for resurrecting mediatomb from, well, its tomb. Apart from some technical improvements, I'm particularly fond of the new logo, which is definitely more cheerful than the old one! :)

I managed to compile gerbera on a Debian Stretch system with very little hassle and I'm also able to start the daemon from the command-line, but I just can't get it to work using systemctl and the .service file (actually: a modified versio of) from the repo.

Currently my service file looks like this:

    [Unit]
    Description=Gerbera Media Server
    After=network.target

    [Service]
    Type=simple
    User=root
    Group=root
    ExecStart=/usr/local/bin/gerbera -c /etc/gerbera/config.xml
    Restart=on-failure
    RestartSec=5

    [Install]
    WantedBy=multi-user.target

So the only modifications I made were changing user/group to root (since I don't have a gerbera user yet) and updating the ExecStart path to gerbera's actual install location.

However, when issuing

    systemctl start gerbera

the journal gives me

    Sep 20 22:09:52 priamos systemd[1]: gerbera.service: Service hold-off time over, scheduling restart.
    Sep 20 22:09:52 priamos systemd[1]: Stopped Gerbera Media Server.
    Sep 20 22:09:52 priamos systemd[1]: Started Gerbera Media Server.
    Sep 20 22:09:52 priamos systemd[22400]: gerbera.service: Failed at step USER spawning /usr/bin/gerbera: No such process
    Sep 20 22:09:52 priamos systemd[1]: gerbera.service: Main process exited, code=exited, status=217/USER
    Sep 20 22:09:52 priamos systemd[1]: gerbera.service: Unit entered failed state.
    Sep 20 22:09:52 priamos systemd[1]: gerbera.service: Failed with result 'exit-code'.
    Sep 20 22:09:57 priamos systemd[1]: gerbera.service: Service hold-off time over, scheduling restart.
    Sep 20 22:09:57 priamos systemd[1]: Stopped Gerbera Media Server.
    Sep 20 22:09:57 priamos systemd[1]: Started Gerbera Media Server.
    ....

Oh, and I *did* make sure that the /etc/gerbera directory does exits.

So am I missing something or is gerbera missing something?

Cheers --

Torsten

### PR DESCRIPTION
**Pull request by elmodaddyb**
Simple walkthrough for adding a systemd daemon for Gerbera.

### CODE REVIEW

**Comment by v00d00** [comment]
This is a good idea. We should make cmake install the unit file in that right place instead of it needing to be copied

**Comment by elmodaddyb** [comment]
@v00d00 - that's a good idea....will work on that.

**Comment by elmodaddyb** [comment]
@v00d00 - I added cmake support for systemd installation of the `gerbera.service` unit file.
I tested with and without MYSQL support.  I have not tested on a system **WITHOUT** systemd

## CMake configure
```
$ cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_MAGIC=1 -DWITH_MYSQL=1 \
-DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 \
-DWITH_EXIF=1 -DWITH_LASTFM=1 -DWITH_FFMPEGTHUMBNAILER=1

-- Found systemd: /usr/bin/pkg-config
-- Configuring systemd unit file: gerbera.service
```

## Installation

```
Install the project...
-- Installing: /etc/systemd/system/gerbera.service
```

**On a side note** - I started a [gerbera-docker](https://github.com/elmodaddyb/gerbera-docker) repository with `Dockerfile` for each distribution.  So that its easier to build/test/deploy locally for different runtimes.  This allows a user to run Gerbera in a container...foregoing all system configuration tasks!!!  My hope is to move this to Gerbera org at some time later.

**Comment by elmodaddyb** [comment]
I tested the cmake build on `macos` which does not have `systemd`.  The build ran as expected and did not product any systemd artifacts.

**Comment by v00d00** [comment]
I will merge this then tidy a couple of bits up.

1. `-- Found systemd: /usr/bin/pkg-config` doesnt make too much sense, so we will just say TRUE until we have a need to find libsystemd
2. Make the systemd stuff optional as some people _really_ dislike systemd

**Comment by elmodaddyb** [comment]
Yea, i agree, `pkg-config` is pretty much useless.  In researching sounds like Linux purists do not like systemd.  However, I find it to be a lot easier to setup/use vs. `init.d/` scripting.  Once I figured out `/init.d/` Fedora changed to `systemd` so a bit of a pain on the move.

https://www.infoworld.com/article/3159124/linux/linux-why-do-people-hate-systemd.html

**Pull request merged**
