### PR TITLE
Implement libupnp hostname validation

### PR DESCRIPTION
**Pull request by whyman**
Set a `UpnpSetHostValidateCallback` to validate that host names match a
configured virtualURL. Produces a warning if requests do not match with link
to the docs to make debugging non-loading UIs more obvious.

Interestingly, libupnp currently seems to have a bug where the returned
UPNP_E_BAD_HTTPMSG is not actually respected, so for now this change
will allow all hostnames until the libupnp bug is fixed...

Fixes: #2326

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
You need at least libupnp 1.14.10 or so.

**Comment by whyman** [comment]
Sigh, `1.14.6` is the earliest. Conan doesn't seem to have anything newer than `1.14.2` :cry: .

**Comment by neheb** [comment]
I assume libnpupnp would also not work.

**Comment by whyman** [comment]
> I assume libnpupnp would also not work.

It should do, this API was actually invented by them and backported

**Comment by neheb** [comment]
Oh interesting.

**Comment by neheb** [comment]
```
../src/server.cc:200:5: error: ‘UpnpSetHostValidateCallback’ was not declared in this scope
  200 |     UpnpSetHostValidateCallback(

```

**Comment by whyman** [comment]
Interestingly for some reason in libnpupnp its called `UpnpSetWebRequestHostValidateCallback`.

I wonder if our friend @medoc92 would mind providing a compatible alias to avoid another ifdef

**Comment by medoc92** [comment]
I'll add an alias.

**Comment by whyman** [comment]
Conan bump PR: https://github.com/conan-io/conan-center-index/pull/8645

**Pull request merged**
