### PR TITLE
treewide: use fmt::to_string instead of std version

### PR DESCRIPTION
**Pull request by neheb**
The former is faster. More info: https://github.com/fmtlib/fmt/issues/326

Signed-off-by: Rosen Penev <rosenp@gmail.com>

I am not sure whether or not this is worth it. Thoughts?

### CODE REVIEW

**Comment by neheb** [comment]
https://www.zverovich.net/2020/06/13/fast-int-to-string-revisited.html indicates it's not much of a win for gcc. it's somewhat of a win with clang at 7%.

**Comment by whyman** [comment]
Ran the numbers how?

If we can get solid proof this is better then I see no harm merging.

**Comment by neheb** [comment]
From that page. fmt::to_string = 83,700,563 , std::string = 65,638,239

**Comment by whyman** [comment]
I think we would see more improvement by changing string concat arround:

`throw_std_runtime_error("invalid object type: " + fmt::to_string(objectType));`

vs


`throw_std_runtime_error("invalid object type: " + std::to_string(objectType));`

is no real gain, where as

`throw_std_runtime_error(fmt::format("invalid object type: {}", objectType));`

Is cleaner and removes the string concats.

**Comment by whyman** [comment]
And equally stuff like:
```
(std::string(XML_XMLNS) + std::to_string(CONFIG_XML_VERSION) + " " + XML_XMLNS + std::to_string(CONFIG_XML_VERSION) + ".xsd").c_str();
```
Should be converted to use fmt too

**Pull request merged**
