### PR TITLE
Feature/dockerfile

### PR DESCRIPTION
**Pull request by tiescher**
Hi all.

I would like to introduce a change to the Dockerfile to be able to easily change the base image.
That would be very helpful for building on other platforms, eg. like ARMv7 with this command w/out modifying the Dockerfile:

  buildah bud -t gerbera:test --build-arg BASE_IMAGE=arm32v7/alpine:3.15 . 

Thanks in advance

tiescher

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
Thank you for your contribution.

**Review by whyman — APPROVED** [review]

**Comment by tiescher** [comment]
Thanks for accepting this change ... and for all the great contributions and efforts you have done to provide such a great UPNP streamer.

**Comment by whyman** [comment]
BTW, we do already have ARMv7 and ARM64 images on Dockerhub :+1:

**Comment by tiescher** [comment]
Yes, saw these ... but I prefer to build my own ones 👍 ...keep me on touch with podman and buildah

**Pull request merged**
