### PR TITLE
use map.emplace

### PR DESCRIPTION
**Pull request by neheb**
allows using std::move.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
How does emplace behave if an entry is already there?

**Comment by neheb** [comment]
From cppref:

```
The element may be constructed even if there already is an element with the key in the container, in which case the newly constructed element will be destroyed immediately. 
```

**Comment by KarlStraussberger** [comment]
This also is a breaking change!

**Comment by whyman** [comment]
I am confused how it makes sense to emplace if you are "moving"? There is no construction going on with a move?

**Comment by neheb** [comment]
Replaced with insert_or_assign.

**Pull request merged**
