### PR TITLE
CI: Drop excluded ubuntu versions as CMake PPA now supports those com…

### PR DESCRIPTION
**Pull request by whyman**
…binations

Apparently fixed for a year now... https://gitlab.kitware.com/cmake/cmake/-/issues/22683#note_1264849

### CODE REVIEW

**Comment by whyman** [comment]
The head checks are failing now .... :see_no_evil:

**Comment by KarlStraussberger** [comment]
Strange enough with
```
--2024-04-10 20:21:52--  https://github.com/fmtlib/fmt/archive/refs/tags/10.2.1.tar.gz
  Resolving github.com (github.com)... 140.82.112.4
  Connecting to github.com (github.com)|140.82.112.4|:443... connected.
  ERROR: cannot verify github.com's certificate, issued by 'CN=Sectigo ECC Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB':
    Unable to locally verify the issuer's authority.
  To connect to github.com insecurely, use `--no-check-certificate'.
```
Do we install `wget`. Had that issue with alpine and could fix it by installing a full version of wget instead of the busybox version.

**Comment by KarlStraussberger** [comment]
` Get:51 http://ports.ubuntu.com/ubuntu-ports focal-updates/main armhf wget armhf 1.20.3-1ubuntu2 [322 kB]`

I remember that 1.20 was the culprit.

**Comment by whyman** [comment]
Even more odd now than a re-run has made it green!

**Comment by KarlStraussberger** [comment]
Used to have that locally when testing the docker things. First run failed to resolve github, second run went straight through. A newer wget fixed that. But I suppose there is none available.

**Comment by whyman** [comment]
Hmm, now this stage fails, on a newer ubuntu?! https://github.com/gerbera/gerbera/actions/runs/8637803626/job/23680837217

**Comment by KarlStraussberger** [comment]
Maybe we should simply disable that again.

**Pull request merged**
