### PR TITLE
some cleanups

### PR DESCRIPTION
**Pull request by neheb**
I'm sure manual review of these is needed.

### CODE REVIEW

**Comment by whyman** [comment]
Does it run?

**Comment by neheb** [comment]
It does yes.

master seems to be broken in a different way though. I can't play anything on any device.

**Comment by whyman** [comment]
Well that sounds quite concerning!

**Comment by neheb** [comment]
There were lots of changes recently so probably to be expected.

**Comment by neheb** [comment]
looks like it's actually this PR. Wonder which commit it is.

**Comment by neheb** [comment]
Oh I see what's happening. It's not master that's broken. It's gerbera with libupnp master. When I switch back to npupnp master, everything works.

**Comment by whyman** [comment]
Can you explain more what the issue is? Things being broken with libupnp is not good as that's what 99 percent of users will do!

**Comment by neheb** [comment]
Yeah but 99% of users will not be using a master build of libupnp and building using its shiny new CMake build :).

The issue is that none of the files play. In the web UI, when pressing a file you get a 0 byte download. On foobar2000, it just says can't find file.

**Comment by neheb** [comment]
Rebased.

**Comment by neheb** [comment]
Anyone?

I've tested this to work fine with foobar2000 mobile.

**Comment by whyman** [comment]
Looks good to me except for the `FILE* f __attribute__((__cleanup__(clean_file)));` which seems a bit C to me.

**Comment by neheb** [comment]
Well, it's a GCC attribute that works with both.

**Comment by neheb** [comment]
Removed GCC cleanup attribute commit.

**Pull request merged**
