### PR TITLE
Minor UI Updates

### PR DESCRIPTION
**Pull request by whyman**

### CODE REVIEW

**Comment by whyman** [comment]
still working on tests.....

Also the screenshot updates seem broken by the latest version of selenium :(

**Comment by KarlStraussberger** [comment]
> Also the screenshot updates seem broken by the latest version of selenium :(

That's why I froze my nodejs environment to chromium  80.

**Comment by whyman** [comment]
Only ~15 tests failing now.... :face_with_head_bandage:

**Comment by whyman** [comment]
Think I may have to give up on this change, I have no desire to try and fix these tests anymore.

I find this jquery UI code quite impenetrable.

**Pull request closed without merging**
