### PR TITLE
#30 add metadata mkv support via libmatroska

### PR DESCRIPTION
**Pull request by pamapa**

### CODE REVIEW

**Comment by pamapa** [comment]
CI fails because it has not matroska installed. Should i by default disable matroska?

**Comment by whyman** [comment]
I dont think it needs to be disabled by default, we just need to add it to the [base image](https://github.com/gerbera/gerbera-ci-base-docker).

**Comment by pamapa** [comment]
cool, i added the needed dev libraries there:
https://github.com/gerbera/gerbera-ci-base-docker/pull/1

**Comment by whyman** [comment]
Thanks, LGTM!

**Pull request merged**
