### PR TITLE
Revert "initialize several unique_ptrs"

### PR DESCRIPTION
**Pull request by KarlStraussberger**
Reverts gerbera/gerbera#1483

Breaks ubuntu:18.04

https://github.com/gerbera/gerbera/runs/2714005392

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
@neheb Have a look at this, please

**Comment by neheb** [comment]
The second commit shouldn't be reverted.

The first is indeed problematic. It's effectively a naive way to avoid allocating a null pointer, which later on becomes non NULL.

**Comment by KarlStraussberger** [comment]
> 
> 
> The second commit shouldn't be reverted.
> 
> The first is indeed problematic. It's effectively a naive way to avoid allocating a null pointer, which later on becomes non NULL.
> 
> edit: oh I see why it fails. PUGIXML has support for move semantics, which seem to not be available with Ubuntu's version.

I can only revert the whole PR. Sorry, at least it was the fastest way to get the build running again. Better to split them up. also.

**Comment by neheb** [comment]
Not a big deal honestly.

**Pull request merged**
