### PR TITLE
Removing sudo dependecy and fixing shellcheck warnings

### PR DESCRIPTION
**Pull request by lgehr**
Hey everybody,
I just recently tried to install gerbera on a fresh FreeBSD Jail and the installation script failed because I did not had sudo installed. So I just changed the scripts. Also this is my first pull request ever so please be kind ;)

Remove the sudo dependecy in the install scripts and added a
if-statement to check if the script is run with superuser access to
    perform the install.
This removes the need to have sudo installed and also has a better
error-handeling if the user types in the root password wrong 3 times.

Fixed shellcheck warnings which should result in robuster code.

### CODE REVIEW

**Comment by elmodaddyb** [comment]
@lgehr - Thanks for posting 👍 .  It looks like the Travis CI build is in failure state with this PR.

https://travis-ci.org/gerbera/gerbera/jobs/421220112

The Travis CI build runs against common C++ architectures to ensure the build is compatible with different runtimes.  You can review the Travis CI failure log to see if there is a way to resolve.

Post your ideas here.  If you have a solution, you can push a change to the same branch, and it will append into this PR request.  This way you can iterate without having to worry about opening/closing the PR.

**Comment by lgehr** [comment]
@elmodaddyb Thanks for your feedback.

I think I found the error. Because the install scripts now need to be called as root we have to do this in the .travis.yml.

**Comment by lgehr** [comment]
I'm pretty confused why the cmake yields error's now. I did not change its call in the script. Will do more research.

**Comment by elmodaddyb** [comment]
@lgehr - I ran the `install-googletest.sh` with similar settings that you committed and all went perfectly fine.

I will try to retest within the Travis Build system to see how it acts.

Thanks

**Comment by elmodaddyb** [comment]
@lgehr - Looks like there is a recent open issue in googletest regarding the same defect we see when building with CMake 2.8 in Travis.

https://github.com/google/googletest/issues/1786

> Oddly Gerbera has a minimum cmake requirement of 3.2

https://github.com/gerbera/gerbera/blob/master/CMakeLists.txt#L1

**Comment by lgehr** [comment]
Thanks for your research. I have no internetconnection at home at the moment. So I could not look into it. I hope to get to it on monday

Am 8. September 2018 06:19:59 MESZ schrieb Eamonn <notifications@github.com>:
>@lgehr have you had a chance to try updating the Travis build to
>cmake3?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gerbera/gerbera/pull/342#issuecomment-419611584

-- 
Gesendet mit pEp für Android.

**Comment by elmodaddyb** [comment]
Looks like the Travis build was successful!!

https://travis-ci.org/gerbera/gerbera/builds/426936301

Great Job @lgehr  🏆

**Comment by elmodaddyb** [comment]
If no objections, I will merge the PR over this weekend.

> Thanks for the patience and contribution!

**Comment by elmodaddyb** [comment]
Sorry for the delay, you can merge when you have time.

**Comment by v00d00** [comment]
Thanks @lgehr! and @elmodaddyb for sorting the PR.

**Pull request merged**
