### PR TITLE
replace C locale functions with std::locale

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
failed. wonder why.

**Comment by KarlStraussberger** [comment]
> 
> 
> failed. wonder why.

Hi, you need to rebase you PRs.
We had to remove a CI check because of weird issues in conan packages when compiling with clang.

**Comment by neheb** [comment]
I tested a simplified version locally:

```
#include <string>
#include <locale>

int main()
{
    std::string temp;
    std::locale glo;
    glo.global(std::locale(""));
    std::locale gloc;
    temp = !gloc.name().empty() ? gloc.name() : "empty";
    printf("Global locale is: %s\n", temp.c_str());
}

It works correctly. I have no idea why it's failing here.
```

**Comment by KarlStraussberger** [comment]
It the ConfigGeneratorTest that segfaults. You need to look into it, maybe does some locale stuff also.

**Comment by neheb** [comment]
No it's not it. Gerbera crashes as well. Maybe it's some weird constructor interaction. Anyway, I'm probably not going to bother figuring it out.

**Pull request closed without merging**
