### PR TITLE
Add minimal CI build

### PR DESCRIPTION
**Pull request by whyman**

### CODE REVIEW

**Comment by neheb** [comment]
```
 /__w/gerbera/gerbera/src/content/content_manager.cc:1303:5: error: 'destroyJS' was not declared in this scope
 1303 |     destroyJS();
      |     ^~~~~~~~~
/__w/gerbera/gerbera/src/content/content_manager.cc:1305:5: error: 'initJS' was not declared in this scope
 1305 |     initJS();
```

I get the same error locally.

**Comment by whyman** [comment]
Well, nice to see the check works! :+1:

**Comment by KarlStraussberger** [comment]
> 
> 
> Well, nice to see the check works! 👍

I've deliberately added that case 😺

**Comment by KarlStraussberger** [comment]
There's quite some work to do on the tests - I need some rest before this.

**Comment by whyman** [comment]
Well that ended up being way more painful than I expected :face_with_head_bandage:

**Comment by KarlStraussberger** [comment]
Hidden treasures.

**Pull request merged**
