### PR TITLE
Sort result of fs::directory_iterator

### LINKED ISSUE #855: How to make UI File System view sort by directory name
Gerbera looks via nfs at my NAS which contains folders with 100+ subfolders. They get displayed in the UI in a - to me at least - random manner. An alphabetical order as a default to me would make more sense. Or do I miss some way for configuration?

### PR DESCRIPTION
**Pull request by KarlStraussberger**
I'm not sure whether this is the most efficient way, but it works! Fixes #855

### CODE REVIEW

**Comment by whyman** [comment]
Marvellous

**Comment by whyman** [comment]
CircleCI sucks

**Comment by KarlStraussberger** [comment]
Obviously my last commit was too early and started a second build job

**Comment by whyman** [comment]
Heh, it just sucks. Rerunning the build now.

We really need some tests (and a rewrite) for the UI backend code

**Comment by ytimenkov** [comment]
This comment needs to be reverted.
`fs::directory_iterator` is an **InputIterator** which means that what it points at becomes invalid as soon as it moves to the next element. However pointers to dereferenced paths are stored.

Double-checked with valgrind:
```
==23857== Thread 4:
==23857== Invalid read of size 8
==23857==    at 0x26094F: size (basic_string.h:902)
==23857==    by 0x26094F: empty (basic_string.h:1003)
==23857==    by 0x26094F: empty (fs_path.h:408)
==23857==    by 0x26094F: std::filesystem::__cxx11::path::filename() const (fs_path.h:1201)
==23857==    by 0x2D703F: web::directories::process() (directories.cc:121)
==23857==    by 0x235243: web::WebRequestHandler::open(UpnpOpenFileMode) (web_request_handler.cc:142)
==23857==    by 0x23658D: web::WebRequestHandler::open(char const*, UpnpOpenFileMode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (web_request_handler.cc:233)
==23857==    by 0x1DC905: Server::registerVirtualDirCallbacks()::{lambda(char const*, UpnpOpenFileMode, void const*, void const*)#2}::operator()(char const*, UpnpOpenFileMode, void const*, void const*) const (server.cc:549)
==23857==    by 0x1DCB7F: Server::registerVirtualDirCallbacks()::{lambda(char const*, UpnpOpenFileMode, void const*, void const*)#2}::_FUN(char const*, UpnpOpenFileMode, void const*, void const*) (server.cc:562)
==23857==    by 0x489AD24: http_SendMessage (httpreadwrite.c:504)
==23857==    by 0x489E170: web_server_callback (webserver.c:1702)
==23857==    by 0x4896368: dispatch_request (miniserver.c:157)
==23857==    by 0x4896368: handle_request (miniserver.c:230)
==23857==    by 0x488F61E: WorkerThread (ThreadPool.c:576)
==23857==    by 0x485E608: start_thread (pthread_create.c:477)
==23857==    by 0x58A3102: clone (clone.S:95)
==23857==  Address 0x179d86f8 is 72 bytes inside a block of size 112 free'd
==23857==    at 0x483D1CF: operator delete(void*, unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==23857==    by 0x2D6D07: _M_release (shared_ptr_base.h:171)
==23857==    by 0x2D6D07: ~__shared_count (shared_ptr_base.h:730)
==23857==    by 0x2D6D07: ~__shared_ptr (shared_ptr_base.h:1180)
==23857==    by 0x2D6D07: ~directory_iterator (fs_dir.h:388)
==23857==    by 0x2D6D07: web::directories::process() (directories.cc:89)
==23857==    by 0x235243: web::WebRequestHandler::open(UpnpOpenFileMode) (web_request_handler.cc:142)
==23857==    by 0x23658D: web::WebRequestHandler::open(char const*, UpnpOpenFileMode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (web_request_handler.cc:233)
==23857==    by 0x1DC905: Server::registerVirtualDirCallbacks()::{lambda(char const*, UpnpOpenFileMode, void const*, void const*)#2}::operator()(char const*, UpnpOpenFileMode, void const*, void const*) const (server.cc:549)
==23857==    by 0x1DCB7F: Server::registerVirtualDirCallbacks()::{lambda(char const*, UpnpOpenFileMode, void const*, void const*)#2}::_FUN(char const*, UpnpOpenFileMode, void const*, void const*) (server.cc:562)
==23857==    by 0x489AD24: http_SendMessage (httpreadwrite.c:504)
==23857==    by 0x489E170: web_server_callback (webserver.c:1702)
==23857==    by 0x4896368: dispatch_request (miniserver.c:157)
==23857==    by 0x4896368: handle_request (miniserver.c:230)
==23857==    by 0x488F61E: WorkerThread (ThreadPool.c:576)
==23857==    by 0x485E608: start_thread (pthread_create.c:477)
==23857==    by 0x58A3102: clone (clone.S:95)
==23857==  Block was alloc'd at
==23857==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==23857==    by 0x55AFE8E: std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==23857==    by 0x2D65A3: directory_iterator (fs_dir.h:372)
==23857==    by 0x2D65A3: web::directories::process() (directories.cc:89)
==23857==    by 0x235243: web::WebRequestHandler::open(UpnpOpenFileMode) (web_request_handler.cc:142)
==23857==    by 0x23658D: web::WebRequestHandler::open(char const*, UpnpOpenFileMode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (web_request_handler.cc:233)
==23857==    by 0x1DC905: Server::registerVirtualDirCallbacks()::{lambda(char const*, UpnpOpenFileMode, void const*, void const*)#2}::operator()(char const*, UpnpOpenFileMode, void const*, void const*) const (server.cc:549)
==23857==    by 0x1DCB7F: Server::registerVirtualDirCallbacks()::{lambda(char const*, UpnpOpenFileMode, void const*, void const*)#2}::_FUN(char const*, UpnpOpenFileMode, void const*, void const*) (server.cc:562)
==23857==    by 0x489AD24: http_SendMessage (httpreadwrite.c:504)
==23857==    by 0x489E170: web_server_callback (webserver.c:1702)
==23857==    by 0x4896368: dispatch_request (miniserver.c:157)
==23857==    by 0x4896368: handle_request (miniserver.c:230)
==23857==    by 0x488F61E: WorkerThread (ThreadPool.c:576)
==23857==    by 0x485E608: start_thread (pthread_create.c:477)
```

**Comment by KarlStraussberger** [comment]
My doubts became true.

I already have a fix in work.

**Pull request merged**
