### PR TITLE
Add log sinks for rotating log files and syslog

### PR DESCRIPTION
**Pull request by KarlStraussberger**

### CODE REVIEW

**Comment by whyman** [comment]
I wonder if we should just ship a log rotate config file instead?

**Comment by KarlStraussberger** [comment]
Also see #789

**Comment by KarlStraussberger** [comment]
> I wonder if we should just ship a log rotate config file instead?

Once it's all done...

**Comment by KarlStraussberger** [comment]
Need some config options for the size, rotation count, syslog facility etc,

**Pull request merged**
