### PR TITLE
Inotify: Handle Inotify access failed

### LINKED ISSUE #3090: "Cannot add inotify watch: Permission denied" for new folders (`cp -a`)
**Describe the bug**
When copying a new music album from my Laptop or Desktop onto my home server's NFS share, Gerbera immediately detects the new folder and tries to add it. It fails with
> warning: Cannot add inotify watch for /data/media/Music/Alben/Coldplay/Viva la Vida or Death and All His Friends: Permission denied
> warning: Cannot add inotify watch for /data/media/Music/Alben/Coldplay/Viva la Vida or Death and All His Friends: Permission denied
> error: Failed to iterate /data/media/Music/Alben/Coldplay/Viva la Vida or Death and All His Friends, Permission denied

When the copy operation is finished, the permissions on the server are correct and Gerbera can read the files in the directories.
I suspect this has something to do with how NFS (or the `cp` tool) handles new folders.

It would be nice if Gerbera would wait for some seconds when a new folder is found and a permission error is encountered, and try again.

**To Reproduce**

0. Share a folder via NFS with second machine. `/etc/exports/` shows:
```
/data/media  boo(rw,sync,no_wdelay,no_subtree_check,no_root_squash,insecure_locks,anonuid=0,anongid=100)
```
1. Use that folder with Gerbera:
```
    <autoscan use-inotify="yes">
      <directory location="/data/media/Music/" mode="inotify" recursive="yes"/>
    </autoscan>
```
2. Copy new music album via NFS into that folder using `cp -a`.
3. Gerbera fails to add inotify watch and fails to scan folder

**Expected behavior**
Gerbera should wait a bit until the directory changes have "settled" and only start its work then.

**Server (please complete the following information):**
 - OS: Debian 12
 - Gerbera Version: v2.1.0-28-g9dd54a98
 - Versions of libraries: 
 - Source: self built from git

**NFS client**
 - Device: Debian 12
 - Client app: mate-terminal

### PR DESCRIPTION
**Pull request by KarlStraussberger**
Closes #3090

### CODE REVIEW

**Comment by cweiske** [comment]
I get an error during compilation:
```
[ 78%] Building CXX object CMakeFiles/libgerbera.dir/src/util/mt_inotify.cc.o
/usr/local/src/gerbera/gerbera-git/src/util/mt_inotify.cc: In member function ‘int Inotify::addWatch(const std::filesystem::__cxx11::path&, uint32_t, unsigned int) const’:
/usr/local/src/gerbera/gerbera-git/src/util/mt_inotify.cc:110:26: error: ‘std::this_thread’ has not been declared
  110 |                     std::this_thread::sleep_for(std::chrono::milliseconds(100));
      |                          ^~~~~~~~~~~
```

(I think that watching for attribute changes would be better)

**Comment by KarlStraussberger** [comment]
> (I think that watching for attribute changes would be better)
Actually, I'm planning for both.

**Comment by cweiske** [comment]
I don't see the message "Retrying {} to add inotify watch" when running gerbera in `--debug` mode with `retry-count=3`, but the music files appear in gerbera pretty fast after some seconds.

A couple of errors appear in the log, though:
> error: Failed to read /data/media/debugmusic/Alben/Viva la Vida or Death and All His Friends: No such file or directory
> error: Exception caught: [/usr/local/src/gerbera/gerbera-git/src/util/grb_fs.cc:274] bool isTheora(const std::filesystem::__cxx11::path&) Error: Error reading /data/media/debugmusic/Alben/Viva la Vida or Death and All His Friends/Coldplay - Viva la Vida or Death and All His Friends - 03 - Lost!.ogg
> ...

But afterwards they are available in the UI.

Did you already implement watching for attribute changes?

**Comment by KarlStraussberger** [comment]
No additional changes, yet. Will try to do some refactoring, before adding more switches.

Obviously, the code change slows import down to get the error when reading files instead of when accessing the directory.

**Comment by KarlStraussberger** [comment]
Had to go back to alpine v3.19 for Minimal build because of some issue in _latest-stable_.

Introduced build names without versions to avoid missing merge preconditions

**Comment by KarlStraussberger** [comment]
@cweiske You can add option
`<autoscan inotify-attrib="yes" ...`

**Comment by cweiske** [comment]
- you define `<xs:enumeration value="auto"/>` but that's not covered by code
- when I delete a folder, gerbera does not detect it anymore and does not remove the virtual items. The first 2 log entries show how the dir-is-deleted is seen, the 3rd is me accessing the album in the web UI:
```
2024-05-24 17:42:48.448  debug: [autoscan_inotify.cc:99] InotifyHandler(): inotify event: 7 mask=DELETE name=ExampleAlbum
2024-05-24 17:42:48.449  debug: [autoscan_inotify.cc:173] getPath(): !AUTOSCAN_IS_GONE: /data/media/debugmusic/Alben/ExampleAlbum
2024-05-24 17:43:38.887  error: [server.cc:622] operator()(): Exception: [/usr/local/src/gerbera/gerbera-git/src/file_request_handler.cc:106] virtual const ClientInfo* FileRequestHandler::getInfo(const char*, UpnpFileInfo*) Error: Failed to open /data/media/debugmusic/Alben/ExampleAlbum/8.ogg: No such file or directory
```
- when I copy the directory to the server, it takes a whole minute until gerbera adds the virtual entries to the web UI - even though `inotify-attrib="yes"` is set. The lines until the empty line is how gerbera detects the folder, and with the "update autoscan" line the album is available in the web ui:
```
2024-05-24 17:50:40.667  debug: [autoscan_inotify.cc:99] InotifyHandler(): inotify event: 7 mask=CREATE name=ExampleAlbum
2024-05-24 17:50:40.667  debug: [autoscan_inotify.cc:173] getPath(): !AUTOSCAN_IS_GONE: /data/media/debugmusic/Alben/ExampleAlbum
2024-05-24 17:50:40.667  debug: [autoscan_inotify.cc:220] doDirectory(): Detected new dir, adding to inotify: /data/media/debugmusic/Alben/ExampleAlbum
2024-05-24 17:50:40.667  debug: [autoscan_inotify.cc:259] doNewFile(): Adding /data/media/debugmusic/Alben/ExampleAlbum
2024-05-24 17:50:40.668  debug: [autoscan.cc:198] updateLMT(): Set autoscan false lmt location: /data/media/debugmusic; prev_modified: 1716565821; last_modified: 1716565821, activeScanCount 0, taskCount: 0

2024-05-24 17:51:31.510  debug: [autoscan.cc:188] setCurrentLMT(): Update autoscan /data/media/debugmusic; location: /data/media/debugmusic; lmt: 0; last_modified: 1716565821, activeScanCount 1, taskCount: 1
2024-05-24 17:51:31.514  debug: [autoscan.cc:188] setCurrentLMT(): Update autoscan /data/media/debugmusic; location: /data/media/debugmusic/Alben/ExampleAlbum; lmt: 0; last_modified: 1716565821, activeScanCount 1, taskCount: 1
2024-05-24 17:51:31.556  debug: [autoscan.cc:188] setCurrentLMT(): Update autoscan /data/media/debugmusic; location: /data/media/debugmusic/Alben/ExampleAlbum; lmt: 1716295720; last_modified: 1716565821, activeScanCount 0, taskCount: 1
```

So currently it does not really work as I would expect :)

**Comment by KarlStraussberger** [comment]
> - you define `<xs:enumeration value="auto"/>` but that's not covered by code

That's for `use-inotify` which somehow never made it into the xsd.

> So currently it does not really work as I would expect :)

Functionality should be back now. Just some forgotten refactoring variable.

**Comment by KarlStraussberger** [comment]
@cweiske found it. Removed directories are not getting `IS_DIR`.

**Comment by cweiske** [comment]
:+1: directory handling works fine:

- When using the new attribute `<autoscan use-inotify="yes" inotify-attrib="yes">` the files get added immediately after the "cp -a" process finishes setting the permissions
- When removing the folder, the music tracks get removed immediately

A new test I found that does not involve `cp -a` or NFS is changing permissions:
1. prepare music folder owned by root with no pemissions for gerbera user (`drwx------`). Files in this folder have read `og+r` permissions
2. copy music folder to Gerbera autoscan directory. Gerbera will detect it but fail to add them (permission denied)
3. change folder permissions so that Gerbera can access the files: `chmod go+rx musicfolder`
4. Gerbera immediately adds the music tracks :checkered_flag: 

Problems:
- When a single file gets deleted from a folder, it is not immediately removed from the web UI - only after a minute or so. (should it be removed immediately?)
- When removing the permissions from a folder, Gerbera keeps the music tracks and does not remove them. I don't know if that's ok or not.

**Comment by KarlStraussberger** [comment]
Thanks for your tests.

It is quite complicated to detect effective permissions being removed. In fact, I can live with that, gerbera is no enterprise content management system.

**Comment by KarlStraussberger** [comment]
Deleting items should be as fast as adding them, but sometimes good things need to take their time.

**Pull request merged**
