### PR TITLE
convert all enum members to upper case

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Rebased.

**Comment by whyman** [comment]
I prefer that we stick with the "WebKit" style: `Enum members should use InterCaps with an initial capital letter.`

To me FULL_UPPER means a macro.

**Comment by neheb** [comment]
OTOH a lot of enums currently use caps.

**Comment by whyman** [comment]
So change those too?

**Comment by neheb** [comment]
:)

**Comment by whyman** [comment]
Are you going to make the requested changes or shall we close this?

**Comment by neheb** [comment]
Working on it. The problem is that compared to this commit the changes are massive.

**Comment by neheb** [comment]
I'll post these by parts. Easier.

**Comment by whyman** [comment]
Needs a rebase

**Comment by neheb** [comment]
Rebased.

**Comment by neheb** [comment]
Rebased.

**Pull request merged**
