### PR TITLE
Refactored caching of ffmpeg thumbnails.

### PR DESCRIPTION
**Pull request by ytimenkov**
Fixes: #861

### CODE REVIEW

**Comment by ytimenkov** [comment]
Some thopughts:
1. I thought having `readBinaryFile` / `writeBinaryFile` using only portable C++ is a good idea, plus `fstream` has support for `fs::path` :D
2. `readTextFile` / `writeTextFile` are almost unused and should be replaced with plain `fstream` (i.e. when reading inotify limit).
3. Maybe whole `Mock_config` should be mocked... Didn't want to go through all usages...

**Comment by neheb** [comment]
Last I compiled this on Fedora 32, it was giving me deprecation warnings. Is this relevant?

**Comment by ytimenkov** [comment]
Which warning? I don't have fedora 32 to test.
I build with gcc-10 on ubuntu 20.04 with -WError.

**Comment by neheb** [comment]
```
In file included from src/metadata/ffmpeg_handler.cc:58:
/usr/include/ffmpeg/libavformat/avformat.h:324:1: warning: struct 'AVFormatContext' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
struct AVFormatContext;
^
src/metadata/ffmpeg_handler.h:48:7: note: previous use is here
class AVFormatContext;
      ^
In file included from src/metadata/ffmpeg_handler.cc:58:
/usr/include/ffmpeg/libavformat/avformat.h:1344:9: warning: 'AVFormatContext' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
typedef struct AVFormatContext {
        ^
src/metadata/ffmpeg_handler.h:48:1: note: did you mean struct here?
class AVFormatContext;
^~~~~
struct
src/metadata/ffmpeg_handler.cc:181:48: warning: 'codec' is deprecated [-Wdeprecated-declarations]
        if ((st != nullptr) && (!videoset) && (as_codecpar(st)->codec_type == AVMEDIA_TYPE_VIDEO)) {
                                               ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:182:17: warning: 'codec' is deprecated [-Wdeprecated-declarations]
            if (as_codecpar(st)->codec_tag > 0) {
                ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:184:29: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                fourcc[0] = as_codecpar(st)->codec_tag;
                            ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:185:29: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                fourcc[1] = as_codecpar(st)->codec_tag >> 8;
                            ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:186:29: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                fourcc[2] = as_codecpar(st)->codec_tag >> 16;
                            ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:187:29: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                fourcc[3] = as_codecpar(st)->codec_tag >> 24;
                            ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:190:50: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                log_debug("FourCC: 0x{:x} = {}", as_codecpar(st)->codec_tag, fourcc);
                                                 ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:197:18: warning: 'codec' is deprecated [-Wdeprecated-declarations]
            if ((as_codecpar(st)->width > 0) && (as_codecpar(st)->height > 0)) {
                 ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:197:50: warning: 'codec' is deprecated [-Wdeprecated-declarations]
            if ((as_codecpar(st)->width > 0) && (as_codecpar(st)->height > 0)) {
                                                 ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:198:56: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                auto resolution = fmt::format("{}x{}", as_codecpar(st)->width, as_codecpar(st)->height);
                                                       ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:198:80: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                auto resolution = fmt::format("{}x{}", as_codecpar(st)->width, as_codecpar(st)->height);
                                                                               ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:205:48: warning: 'codec' is deprecated [-Wdeprecated-declarations]
        if ((st != nullptr) && (!audioset) && (as_codecpar(st)->codec_type == AVMEDIA_TYPE_AUDIO)) {
                                               ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:207:17: warning: 'codec' is deprecated [-Wdeprecated-declarations]
            if (as_codecpar(st)->sample_rate > 0) {
                ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:208:30: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                samplefreq = as_codecpar(st)->sample_rate;
                             ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:213:27: warning: 'codec' is deprecated [-Wdeprecated-declarations]
                audioch = as_codecpar(st)->channels;
                          ^
src/metadata/ffmpeg_handler.cc:75:27: note: expanded from macro 'as_codecpar'
#define as_codecpar(s) s->codec
                          ^
/usr/include/ffmpeg/libavformat/avformat.h:884:5: note: 'codec' has been explicitly marked deprecated here
    attribute_deprecated
    ^
/usr/include/ffmpeg/libavutil/attributes.h:94:49: note: expanded from macro 'attribute_deprecated'
#    define attribute_deprecated __attribute__((deprecated))
                                                ^
src/metadata/ffmpeg_handler.cc:348:9: warning: 'thumbnail_size' is deprecated: use video_thumbnailer_set_size() [-Wdeprecated-declarations]
    th->thumbnail_size = config->getIntOption(CFG_SERVER_EXTOPTS_FFMPEGTHUMBNAILER_THUMBSIZE);
        ^
/usr/include/libffmpegthumbnailer/videothumbnailerc.h:35:63: note: 'thumbnail_size' has been explicitly marked deprecated here
    int                         thumbnail_size __attribute__((deprecated("use video_thumbnailer_set_size()"))); /* default = 128 (deprecated, use video_thumbnailer_set_size)*/
                                                              ^
```

**Comment by whitesnake-pl** [comment]
@ytimenkov thanks for the fix. Can you please confirm the logic behind the way cache works supports the same source video/image file image names? This is to ensure that once in a large video/image libraries where we may have multiple files with the same names thumbnails are not overwritten with the "latest" file.

**Comment by ytimenkov** [comment]
@whitesnake-pl 

If you look at `CachePathAppendsAbsolute` it contains expected transformation from movie name to cached thumbnail location.

It explicitly keeps original file name *and* extension *and* absolute path so only collision I can think of is on windows of only drive differs (that case I didn't check).

If you have a concrete example of colliding paths I'll be glad to add it into the test.

**Comment by ytimenkov** [comment]
However neither this nor previous implementation checked for originals mtime, so if you replace the file the thumbnail won't be regenerated.

Another thing I've noticed is that thumbnails may get stuck on the clients cache: e.g. vlc just keeps a file per URL, so if I rescan database ids will change (ids starting from 1 will be used for different real files in gerbera) and thumbnails will be completely random.

**Comment by whitesnake-pl** [comment]
thanks, I imagine i.e. the following folder structure situation is added with inotify autoscan option

/storage/images/2020/04
image-1.jpg
image-2.jpg
image-3.jpg
image-n.jpg

/storage/images/2020/05
image-1.jpg
image-2.jpg
image-n.jpg

In above situation can we test that thumbnails 1, 2 and n from folder "/storage/images/2020/04" are not overwritten with the thumbnails from 1, 2 and n from folder "/storage/images/2020/05"

**Comment by whyman** [comment]
Nice! LGTM.

**Comment by ytimenkov** [comment]
@neheb 

I've glanced through the messages you've posted.

I think this mostly related to CMake version or how things are found: on Ubuntu headers are in `/usr/include/x86_64-linux-gnu/libavformat/avformat.h` which is a system path and thus doesn't generate warnings. You have `ffmpeg` subfolder which is added (I suppose) via `-I` and thus treated as a user code.

Interestingly CMake adds includes for new-style config packages via `-isystem`, for example: I have `-isystem /home/dev/fmt/include`. Probably you could get the same behavior by adding `SYSTEM` to `include_directories(${FFMPEG_INCLUDE_DIR})`.

1. `struct AVFormatContext` vs `class AVFormatContext`: I agree with the warning and I think it's generally a bad idea (error-prone) to forward-declare stuff from other libraries.
Technically the header could be included or this can be worked around by moving functions using `AVFormatContext` into the implementation file and making them free functions (like cache base path calculation I did).

2.  `warning: 'codec' is deprecated`: Means that test `CHECK_STRUCT_HAS_MEMBER` in `FindFFMPEG.cmake` doesn't pass or another Find module is used, because otherwise Gerbera should use `codecpar` member. This needs to be debugged on a particular system :(

Since this PR is closed I suggest moving this discussion into a separate issue.

**Comment by ytimenkov** [comment]
@whitesnake-pl 
Was too slow to add a new test, but I can confirm that following test passes:
```
TEST(Thumbnailer_Cache, CacheUniquePaths)
{
    const auto cache_base = fs::path { "/storage/cache" };
    // 2 similar paths with same file name.
    auto path1 = getThumbnailCachePath(cache_base, "/storage/images/2020/04/image-1.jpg");
    auto path2 = getThumbnailCachePath(cache_base, "/storage/images/2020/05/image-1.jpg");
    EXPECT_NE(path1, path2);
}
```

**Comment by whyman** [comment]
@ytimenkov feel free to stick the extra test in a PR

**Pull request merged**
