### PR TITLE
Extract command line argument handling to Runtime class

### PR DESCRIPTION
**Pull request by KarlStraussberger**
This fixes several issues:
- Pidfile is always removed on exit now
- Entries from config file are correctly overwritten by command line arguments on restart
- SIGHUP seems to work as well

### CODE REVIEW

**Comment by cweiske** [comment]
I get compilation errors:
```
[ 99%] Building CXX object CMakeFiles/gerbera.dir/src/main.cc.o
/usr/local/src/gerbera/gerbera-git/src/main.cc:75:10: error: ‘condition_variable’ in namespace ‘std’ does not name a type
   75 |     std::condition_variable cond;
      |          ^~~~~~~~~~~~~~~~~~
/usr/local/src/gerbera/gerbera-git/src/main.cc: In function ‘void signalHandler(int)’:
/usr/local/src/gerbera/gerbera-git/src/main.cc:115:10: error: ‘struct<unnamed>’ has no member named ‘cond’
  115 |     _ctx.cond.notify_one();
      |          ^~~~
/usr/local/src/gerbera/gerbera-git/src/main.cc: In function ‘int main(int, char**, char**)’:
/usr/local/src/gerbera/gerbera-git/src/main.cc:282:18: error: ‘struct<unnamed>’ has no member named ‘cond’
  282 |             _ctx.cond.wait(_ctx.lock);
      |                  ^~~~
make[2]: *** [CMakeFiles/gerbera.dir/build.make:76: CMakeFiles/gerbera.dir/src/main.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/gerbera.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
[...]
```

**Comment by KarlStraussberger** [comment]
> I get compilation errors on Debian 12:
> 
> ```
> [ 99%] Building CXX object CMakeFiles/gerbera.dir/src/main.cc.o
> /usr/local/src/gerbera/gerbera-git/src/main.cc:75:10: error: ‘condition_variable’ in namespace ‘std’ does not name a type
>    75 |     std::condition_variable cond;
>       |          ^~~~~~~~~~~~~~~~~~
> /usr/local/src/gerbera/gerbera-git/src/main.cc:66:1: note: ‘std::condition_variable’ is defined in header ‘<condition_variable>’; did you forget to ‘#include <condition_variable>’?
>    65 | #include <sys/wait.h>
>   +++ |+#include <condition_variable>
>    66 | #include <unistd.h>
> /usr/local/src/gerbera/gerbera-git/src/main.cc: In function ‘void signalHandler(int)’:
> /usr/local/src/gerbera/gerbera-git/src/main.cc:115:10: error: ‘struct<unnamed>’ has no member named ‘cond’
>   115 |     _ctx.cond.notify_one();
>       |          ^~~~
> /usr/local/src/gerbera/gerbera-git/src/main.cc: In function ‘int main(int, char**, char**)’:
> /usr/local/src/gerbera/gerbera-git/src/main.cc:282:18: error: ‘struct<unnamed>’ has no member named ‘cond’
>   282 |             _ctx.cond.wait(_ctx.lock);
>       |                  ^~~~
> make[2]: *** [CMakeFiles/gerbera.dir/build.make:76: CMakeFiles/gerbera.dir/src/main.cc.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/gerbera.dir/all] Error 2
> make: *** [Makefile:156: all] Error 2
> [...]
> ```

That was a good finding, because it revealed that we still have some header nesting that brings in hidden dependencies

**Comment by cweiske** [comment]
When using cd618bc I have problems:
- First SIGHUP worked
- After the second SIGHUP, VLC did not find the UPnP server anymore
- Third had the same problem

Restarting the gerbera service via systemctl made it reappear in VLC.

(Also, I get unnecessary warnings for added inotify watches in the log)

**Comment by KarlStraussberger** [comment]
Many thanks for looking into it already.

I also saw the warnings, seems that we have to remove the registered watches.

**Comment by cweiske** [comment]
The 2nd SIGHUP still does not bring the server up again. After 30 seconds I get errors:
```
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: Restarting Gerbera!
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: Loading configuration from: /etc/gerbera/config.xml
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: Parsing configuration...
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: Configuration load succeeded.
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: Validating configuration...
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: Configuration check succeeded.
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: Loading 0 configuration items from database
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: default-import.js
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: default-import.js
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: default-import.js
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: default-import.js
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: default-import.js
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: default-import.js
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: Initialising UPnP with interface: <unset>, port: 49152
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: IPv4: Server bound to: 192.168.3.3:49152
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: IPv6: Server bound to: fe80::96c6:91ff:fe19:a0b4:49152
Jun 07 13:57:17 dojo gerbera[2061835]: 2024-06-07 13:57:17   info: IPv6 ULA/GLA: Server bound to: fdc3:e153::3:49152
Jun 07 13:57:47 dojo gerbera[2061835]: 2024-06-07 13:57:47  error: Could not restart Gerbera
Jun 07 13:57:47 dojo gerbera[2061835]: 2024-06-07 13:57:47  error: UpnpUnRegisterClient failed (-100)
Jun 07 13:57:47 dojo gerbera[2061835]: 2024-06-07 13:57:47  error: UpnpUnRegisterRootDevice failed (-100)
```

After the two sighups, using `systemctl` to restart gerbera does not work (or at least hangs a long time).

**Comment by KarlStraussberger** [comment]
The effect I experience looks like something is running in the background and eating away my CPU time. Shutdown seems to be incomplete to that respect.

**Comment by cweiske** [comment]
45216c5e also exhibits the problem that gerbera takes 100% cpu upon the second sighup and fails to register the upnp services.

Please use the draft functionality for PRs here on github if you're still on it so that I don't test unnecessarily.

**Comment by KarlStraussberger** [comment]
> [45216c5](https://github.com/gerbera/gerbera/commit/45216c5ea7bd2dbdb208341b134b2f364bb18865) also exhibits the problem that gerbera takes 100% cpu upon the second sighup and fails to register the upnp services.
> 
> Please use the draft functionality for PRs here on github if you're still on it so that I don't test unnecessarily.

It's been a hassle with the masked signals. Should work now. Did not test with clients, yet.

**Comment by cweiske** [comment]
VLC finds Gerbera even after 10 SIGHUPs now :)
I also don't see 100% CPU usage anymore after SIGHUPs.
Restarting gerbera with `systemctl` works fine after reloading with SIGHUP a couple of times as well.

**Comment by KarlStraussberger** [comment]
> VLC finds Gerbera even after 10 SIGHUPs now :) I also don't see 100% CPU usage anymore after SIGHUPs. Restarting gerbera with `systemctl` works fine after reloading with SIGHUP a couple of times as well.

@cweiske  Thank you for testing and confirming.

**Pull request merged**
