### PR TITLE
Support filtering transcoding profiles

### LINKED ISSUE #1738: Alow client and codec specific transcoding
I've tried using `client-flags` with transcoding profiles and they work just fine. However this issue is about ability to differentiate between codecs used in a specific container (or mimetype), and choose transcoding profile based on that.

Thus, "Allow codec specific transcoding" would be super-awesome!

_Originally posted by @kyak in https://github.com/gerbera/gerbera/issues/1201#issuecomment-890967545_

### PR DESCRIPTION
**Pull request by KarlStraussberger**
- by client flag
- by content type

closes #1738

### CODE REVIEW

**Comment by hmoffatt** [comment]
Thanks @KarlStraussberger , looks interesting. How do I know the DLNA profile of an item in order to use this?

I had a look at the properties of a DSF file and a Wavpack file in the web UI and I didn't see anything that matches.

**Comment by KarlStraussberger** [comment]
Got to the web page and check out the `details` of a file (it should contain acodec and vcodec). Then you can create an entry like
```
<contenttype-dlnaprofile>
...
	<map from="dsd-x265-aac" to="DSF_X265"/>
	<map from="mp4-h264-aac" to="AVC_MP4_MP_HD_720p_AAC"/>
...
</contenttype-dlnaprofile>

```
This goes into transcoding
```
<mimetype-profile-mappings>
...
	<transcode mimetype="audio/x-dsd" source-profile="DSF_X265" client-flags="0x10" using="vlcmpeg"/>
...
</mimetype-profile-mappings>

```

**Comment by hmoffatt** [comment]
Aha, I see sec:acodec for my audio files. Is that the one?

The wavpack DSF file just shows as wavpack.

**Comment by KarlStraussberger** [comment]
That's it. If you don't have a video codec `dsd--aac` should work :confused:

**Pull request merged**
