### PR TITLE
clang fixes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
weird CI failure. These fixes are just stylistic.

**Comment by KarlStraussberger** [comment]
Unbuntu 20.04 is removing `clang-9`. Hold on until we changed CI check.

**Comment by KarlStraussberger** [comment]
Please rebase that new check is getting active.

**Comment by neheb** [comment]
```
--- a/src/config/config_setup.cc
+++ b/src/config/config_setup.cc
@@ -149,9 +149,6 @@ size_t ConfigSetup::extractIndex(const std::string& item)
     return i;
 }

-const std::string_view ConfigSetup::ROOT_NAME = "config";
-const std::string_view ConfigSetup::ATTRIBUTE = "attribute::";
-
 void ConfigStringSetup::makeOption(const pugi::xml_node& root, const std::shared_ptr<Config>& config, const std::map<std::string, std::string>* arguments)
 {
     bool trim = true;
diff --git a/src/config/config_setup.h b/src/config/config_setup.h
index b4f97fa1..75023d33 100644
--- a/src/config/config_setup.h
+++ b/src/config/config_setup.h
@@ -91,8 +91,8 @@ protected:
     }

 public:
-    static const std::string_view ROOT_NAME;
-    static const std::string_view ATTRIBUTE;
+    static constexpr std::string_view ROOT_NAME = "config";
+    static constexpr std::string_view ATTRIBUTE = "attribute::";

     pugi::xpath_node_set getXmlTree(const pugi::xml_node& element) const;

--
```

seems to not work. wonder why.

**Comment by KarlStraussberger** [comment]
What's the message you get, "not working" leaves some space for interpretation.

**Comment by neheb** [comment]
> What's the message you get, "not working" leaves some space for interpretation.

CI failure. Specifically CI validation / cpp (gcc 9, gcc-9, g++-9) (pull_request)

**Comment by neheb** [comment]
https://github.com/gerbera/gerbera/runs/2595757508?check_suite_focus=true

**Comment by KarlStraussberger** [comment]
That's the js test timing issue - normally we rerun the test and then it passes. No need to push again - we never know whether you're finished or kicking the tests

**Comment by neheb** [comment]
hmm works now. weird.

**Comment by KarlStraussberger** [comment]
``std::data`` may be more generic (which is helpful in generic code), but it makes code less readable and it ends up in calling `.data()`, so please revert.

**Comment by neheb** [comment]
Reverted.

**Pull request merged**
