### PR TITLE
some changes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
Hmm for the ffmpeg find_if change, I wonder if it's better to use all_of instead.

**Review by KarlStraussberger — CHANGES_REQUESTED** [review]
There is no need to reformat 

-  src/database/mysql/mysql_create_sql.h
and
- src/database/sqlite3/sqlite3_create_sql.h 

the files are generated

**Comment by neheb** [comment]
Removed.

**Comment by whyman** [comment]
Isnt `e` glibc specific? Is it supported by e.g. musl

**Comment by neheb** [comment]
Yes it is.

**Comment by neheb** [comment]
https://git.musl-libc.org/cgit/musl/tree/src/stdio/fopen.c#n23

**Review by KarlStraussberger — APPROVED** [review]

**Comment by KarlStraussberger** [comment]
Worst thing possible is that there is an environment which does not compile.

**Pull request merged**
