### PR TITLE
remove custom merge function

### PR DESCRIPTION
**Pull request by neheb**
std::map::merge() is equivalent.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
note that there's a test case for this that passes.

**Comment by whyman** [comment]
Good to know the test passes, but the patch should remove the test too, as that method no longer exists.

**Comment by neheb** [comment]
Removed.

**Comment by whyman** [comment]
Thanks!

**Pull request merged**
