### PR TITLE
replace all lock_guard with scoped_lock

### PR DESCRIPTION
**Pull request by neheb**
SonarLint reports the latter to be better.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
Do we not need some changes to pass in mutexes in some places? You can construct a mutexless scoped_lock right? But not a mutexless lock_guard

**Comment by neheb** [comment]
I don't think so.

Anyway, added CTAD commit. Simplifies things I think.

**Comment by neheb** [comment]
Added comment from SonarLint in the first commit.

**Comment by whyman** [comment]
@KarlStraussberger one to keep an eye on and revert if there is trouble.

**Comment by KarlStraussberger** [comment]
I was planning for a smoke test during the weekend anyway.

**Comment by neheb** [comment]
Second commit is faulty. No idea why.

**Comment by whyman** [comment]
So needs a revert?

**Comment by neheb** [comment]
Or a fix. I can't figure out what's wrong with it. Maybe CTAD's not working right.

**Pull request merged**
