### PR TITLE
Fix processing for M_DATE and M_CREATION_DATE on FFmpeg handler.

### PR DESCRIPTION
**Pull request by mlaerd**
On ffmpeg_handler.cc there is a issue in meta data processing for M_DATE and M_CREATION_DATE. 

https://github.com/gerbera/gerbera/blob/042e0404549159f97e5211915bc46e3529bf1241/src/metadata/ffmpeg_handler.cc#L135-L138

https://github.com/gerbera/gerbera/blob/042e0404549159f97e5211915bc46e3529bf1241/src/metadata/ffmpeg_handler.cc#L143-L145

`if (emptyProperties[M_DATE])` and `if (emptyProperties[M_CREATION_DATE])` are always **false**.
Because `emptyProperties` are created by `propertyMap`  
https://github.com/gerbera/gerbera/blob/042e0404549159f97e5211915bc46e3529bf1241/src/metadata/ffmpeg_handler.cc#L102-L105
that is https://github.com/gerbera/gerbera/blob/042e0404549159f97e5211915bc46e3529bf1241/src/metadata/ffmpeg_handler.h#L68-L78
, where both M_DATE and M_CREATION_DATE are not included.

I want to add them and refine the M_DATE and M_CREATION_DATE processing.

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
Can you try to `push --force` to make the RTD issue go away

**Comment by KarlStraussberger** [comment]
Also, you should make sure that `date` and `creation_date` are not mixed up, i.e date ends up in `M_CREATION_DATE`.

**Comment by mlaerd** [comment]
I confirmed date and creation_date are not mixed up by importing a mp4 video file. Here is  a screen shot.

test

**Comment by KarlStraussberger** [comment]
Thank you

**Comment by mlaerd** [comment]
Thanks!

**Pull request merged**
