### PR TITLE
remove Debian 10 compatibility wrappers

### PR DESCRIPTION
**Pull request by neheb**
Debian 11 is already out, which fixes this issue.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
can't those folks run docker?

**Comment by KarlStraussberger** [comment]
No, because they ran it on the system for ages. Most people don't upgrade within a week.

**Comment by neheb** [comment]
Wonder if for Debian 10 it would be a good idea to recompile all C++ dependencies with LLVM libc++ and link them statically.

**Comment by whyman** [comment]
Lets revisit this in a year or so...

**Pull request closed without merging**
