### PR TITLE
Albumartist

### PR DESCRIPTION
**Pull request by astylos**
Fix for #749

### CODE REVIEW

**Comment by astylos** [comment]
Why do all the updates I've pulled into my for show here?

**Comment by ytimenkov** [comment]
> Why do all the updates I've pulled into my for show here?

That's how git works... They normally should be empty ones (just having 2 parents).

If you want to remove those (usually a good idea before submitting a PR) you can do rebase on `upstream/master`.
(If you didn't have any conflicts it's the easiest way, otherwise I would go with `merge --squash` into a new branch started from master and then either force-pushing to the same branch or creating a new PR).

**Comment by whyman** [comment]
I'm not certain that this fix is right, something else must be broken as it has worked fine since `1.1.0` 3 years ago. It has some special chars, so wondering if its different behaviour with the new XML lib?

**Comment by astylos** [comment]
I've been having this issue for quite some time, but never bothered to look into it. It's only reading #749 that i decided to check if it was same issue i was seeing. But agree it could also be an issue with xml and how it gets encoded. 

How did current tag mapping come about? Looks like gerbera isn't the only one having issues with this: [***](url). The xml in the final comment looks like what gerbera should be emitting if using role is the way to go.

**Comment by astylos** [comment]
> > Why do all the updates I've pulled into my for show here?
> 
> That's how git works... They normally should be empty ones (just having 2 parents).
> 
> If you want to remove those (usually a good idea before submitting a PR) you can do rebase on `upstream/master`.
Thanks

**Comment by pamapa** [comment]
i work a lot with rebase, it keeps the changes lime and nice. You do not get any virtual merge commits, etc...

1. make sure your local master is up to date
  - git checkout master
  - git pull master upstream
  - git push

2. rebase feature branch
  - git checkout <feature/branch>
  - git rebase master # sometimes needs fixing conflics
  - git push --force origin <feature/branch>

3. if you want to change you last commit
  - git add <changed files>
  - git commit --amend
  - git push --force origin <feature/branch>

**Comment by pamapa** [comment]
@astylos 
That fix will work for all new read in metadata. Additional to that a db migration step is needed for all users which still have the wrong string in their db. Like described here: https://github.com/gerbera/gerbera/issues/707#issuecomment-602263434

**Comment by whyman** [comment]
Closing this as per https://github.com/gerbera/gerbera/issues/749#issuecomment-615246006

> 
> Ive taken a look into this.
> 
> The issue here that the special code that handeld the album artist got lost during the removal of the legacy mxml stuff.
> 
> upnp:artist@role[AlbumArtist] should not end up in the XML. It needs to be rendered as <upnp:artist role="AlbumArtist">
> 
> Here is the original commit: b31f659 where the special case was added.
> 
> This should be pretty easy to restore with the nice new XML library.

**Pull request closed without merging**
