### PR TITLE
CI: Upload debs to pkg.gerbera.io

### PR DESCRIPTION
**Pull request by whyman**
Upload to s3 compatible storage with endpoint at pkg.gerbera.io

Will need to update docs once everything is confirmed to work OK.

Tested locally and its fine.

Script changes are to move the dep installs into the conditional, to avoid rebuilding everytime I was trying an upload.

### CODE REVIEW

**Comment by whyman** [comment]
Ah, this workflow is only run on version tags and master, so might have to merge and :crossed_fingers:

**Comment by whyman** [comment]
If I magically find time might need to do something about the JS tests :scream_cat: 

Also love that riscv64 is in there now too! So awesome.

**Comment by KarlStraussberger** [comment]
Great to silence the missing repo thing after months.

**Comment by whyman** [comment]
Merging and lets see how it goes :pray:

**Comment by KarlStraussberger** [comment]
> If I magically find time might need to do something about the JS tests 🙀
> 
> Also love that riscv64 is in there now too! So awesome.

Upgrade to boostrap5. Was looking in and out again 😦 Not enough time atm.

**Comment by whyman** [comment]
:red_circle: https://github.com/gerbera/gerbera/actions/runs/8637552741/job/23679977293 :fire:

**Comment by KarlStraussberger** [comment]
Needs some quotes?

**Comment by whyman** [comment]
Yeah quotes would have solved it I think, but decided to pass it via envs instead https://github.com/gerbera/gerbera/pull/3049

**Pull request merged**
