### PR TITLE
Use getCdsObject to retrieve metadata for m3u playlist

### PR DESCRIPTION
**Pull request by grb43**
Follow up to Issue #406. I have messed around with the playlist.js script and can now see album and artist on my uPnP clients. I am very much a novice with js, but somebody may find it useful. I don't have enough knowledge to tackle pls playlists.

### CODE REVIEW

**Comment by v00d00** [comment]
@elmodaddyb would probably be best to review this.

It also looks like this has broken a test?

**Comment by elmodaddyb** [comment]
This looks cool.  The `getCdsObject` will create the playlist object, if it doesn't find it...

The tests fail because the `getCdsObject` duktape function needs to proxy the mock calls of the `getCdsObject` function within the test

https://github.com/gerbera/gerbera/blob/master/test/test_script/test_internal_m3u_playlist.cc#L87

> I will try to create the changes in next few days to support the testing of this....

**Comment by elmodaddyb** [comment]
Good News, I was able to work out the pattern for testing this capability.  I will patch up the test suite and post back in a day or so.

**Comment by elmodaddyb** [comment]
@grb43 - I was able to make the necessary test driven changes to support this behavior.

> All that remains is a real-time test of the playlist script to confirm it works OK

**Comment by elmodaddyb** [comment]
@grb43 - I opened #413 to solve the build failures faced with this PR.

If you agree we can close this PR and merge #413

**Comment by grb43** [comment]
@elmodaddyb Great, many thanks.

**Pull request closed without merging**
