### PR TITLE
replace various tests with static_assert

### PR DESCRIPTION
**Pull request by neheb**
No need to test these at runtime.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
I guess you want ASSERT_TRUE/FALSE

**Comment by neheb** [comment]
That's just a normal assert.

**Comment by whyman** [comment]
Okay, EXPECT_TRUE then

**Comment by neheb** [comment]
replaced with ASSERT

**Comment by KarlStraussberger** [comment]
The advantage of `EXPECT...` is that the test framework handles stuff and reports test failures correctly. Please switch over to the proper methods.

**Pull request closed without merging**
