### PR TITLE
use more CTAD

### PR DESCRIPTION
**Pull request by neheb**
Happens to avoid extra {}.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Also did conversions to string_view since it seems to work better in constexpr context. Well, maybe future PR.

**Comment by neheb** [comment]
Compiles now.

**Comment by KarlStraussberger** [comment]
I don't see the benefit of this change. Speed? Size? The code looks more complicated as before.

**Comment by neheb** [comment]
No speed or size difference. It's all done in constexpr context, so it generates the same assembly. Main benefit is to get rid of the explicit size parameter. CTAD does not work for just one parameter.

There was an experiment I did once where I imported a constexpr version of map (without insertion of course) and used that instead of these arrays. That one resulted in a slightly smaller binary. I have no idea why.

**Comment by whyman** [comment]
Im not sure this is any improvement, so in this scenario I think its always best to stick with what is proven.

**Pull request closed without merging**
