### PR TITLE
Complete Gerbera UI

### PR DESCRIPTION
**Pull request by elmodaddyb**
* Add delete, edit, download for Gerbera Items
* Implement Add Item for filesystem, refactor trail.
* Separate Tree and Trail implementation
* Add virtual item, refactor overlay
* Refactor e2e for signal and stability
* Solve negative case wait condition
* Stabilize unit and e2e tests, refactor editor overlay
* Restrict editor fields based on types
* Support all edit types save to server
* Add Object save support in editor and items
* Refresh parent when container modified
* Autoscan overlay support
* Fix e2e test for autoscan overlay
* Add autoscan save ability with timed, none, inotify types. Add toast
* Add Gerbera Updates and centralize messaging
* Convert to Bootstrap 4 beta-2, FontAwesome, Tether, Popper
* Add paging support to Gerbera Items
* Support edit existing autoscan folder
* Add update polling for long running server tasks
* Add error checking on request and other status scenarios
* Improve sizeable area for different resolutions
* Improve active updates to UI
* Support edit autoscan from trail, improve Update UI by ids
* Update readme information
* Bump version
* Add license notice to files

### CODE REVIEW

**Comment by elmodaddyb** [comment]
This is a whopper of a PR.  Sorry to hold up so much code change, but didn't feel right delivering unusuable UI features.

Below is a summary of the feature set.

Gerbera UI changes include:
## Vendor Updates
- Bootstrap 4.0.0-beta.2
- FontAwesome Icons

## Gerbera Tree
- Badge Autoscan folders
- Edit Autoscan folder from badge
- Expand folder on click

## Gerbera Items
- Download Link & Icon
- Edit Item
- Delete Item

## Gerbera Trail
#### From Database
- Add New Item
- Edit Item
- Edit Autoscan
- Delete Item
- Delete All Items
#### From Files
- Add Item
- Add Autoscan

## Gerbera Updates
- Track outstanding autoscan tasks on server (with status messages)
- Track outstanding add tasks on server (with status messages)
- Update UI with changes from server tasks
- Show status message on Add, Edit, Delete tasks
- Show status message on failed server tasks or client errors.

**Comment by elmodaddyb** [comment]
Here is the test specification output for end-to-end tests
```
/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js run test:e2e --scripts-prepend-node-path=auto

> gerbera-web@0.0.1 test:e2e /development/gerbera/gerbera-web
> concurrently --success first --kill-others "npm start" "npm run e2e"
 > gerbera-web@0.0.1 e2e /development/gerbera/gerbera-web
 > mocha "test/e2e"
 > gerbera-web@0.0.1 start /development/gerbera/gerbera-web
 > node index.js
 Mock webserver listenting on : 3000

   The add new object
     ✓ a gerbera tree db item container adds new object with parent id (8091ms)

   The autoscan overlay
     ✓ a gerbera tree fs item container opens autoscan overlay when trail add autoscan is clicked
     ✓ autoscan displays message when properly submitted to server (7545ms)
     ✓ an existing autoscan item loads edit overlay

   The gerbera delete item
     ✓ deletes item from the list when delete is clicked (6706ms)

   The invalid session error handler
     ✓ displays a popup when invalid session is detected from server

   The gerbera items
     ✓ loads the related items when tree item is clicked
     ✓ a gerbera item contains the edit icon
     ✓ a gerbera item contains the download icon
     ✓ a gerbera item contains the delete icon
     ✓ loads child tree items when tree item is expanded
     ✓ a gerbera file item does not contain any modify icons
     ✓ a gerbera file item contains an add icon
     ✓ the gerbera items contains a pager that retrieves pages of items

   The login action
     ✓ hides the login form when no authentication is required
     ✓ shows the login form when no session exists yet and accounts is required
     ✓ requires user name and password to submit the login form (5588ms)
     ✓ when successful login show logout button, and show form on logout

   The logout action
     ✓ disables the database and filetype menus upon logout

   The menu bar
     ✓ without logging in the database and filetype menus are disabled
     ✓ enables the database and filetype menus upon login
     ✓ loads the parent database container list when clicking Database
     ✓ loads the parent filesystem container list when clicking Filesystem
     ✓ clears the tree when Home menu is clicked

   The overlay page
     ✓ shows the edit overlay when edit is clicked and contains details
     ✓ on click of db add item, shows the modal
     ✓ selected object defaults class when selected

   The overlay item type selection
     ✓ only shows type, title and class when adding container type (2581ms)
     ✓ only shows title, location, class, desc, mime when adding item type
     ✓ only shows title, location, class, desc, mime, actionScript, state when adding activeItem type
     ✓ only shows title, location, class, desc, mime, protocol when adding external_url type
     ✓ only shows title, location, class, desc, mime when adding internal_url type

   The overlay load item
     ✓ loads a container item to edit with correct fields populated
     ✓ loads an active item to edit with correct fields populated
     ✓ loads an external url to edit with correct fields populated
     ✓ loads an simple item to edit with correct fields populated
     ✓ loads an internal url to edit with correct fields populated

   The gerbera trail
     ✓ a gerbera tree item shows an add icon in the trail but not delete item
     ✓ a gerbera tree db item container shows delete icon and add icon in the trail

   39 passing (2m)
```

**Comment by elmodaddyb** [comment]
Here is the test specification for the unit tests
```
/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js test --scripts-prepend-node-path=auto

> gerbera-web@0.0.1 test /development/gerbera/gerbera-web
> karma start karma.conf.js


START:
11 11 2017 15:58:14.407:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
11 11 2017 15:58:14.408:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
11 11 2017 15:58:14.413:INFO [launcher]: Starting browser PhantomJS
11 11 2017 15:58:14.609:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket fPYCpoUE02bZvBbXAAAA with id 744460
  Gerbera UI App
    initialize()
      ✔ retrieves the configuration from the server using AJAX
      ✔ reports an error when the ajax calls fails
      ✔ stores the TYPE and SID cookies to the document
      ✔ defaults the TYPE to `db` when none is set
      ✔ initializes all GERBERA components when logged in
  Gerbera Auth
    checkSID()
      ✔ calls the server for a new SID and sets the cookie for SID
      ✔ calls GERBERA.App.error when the server call fails
    SID()
      ✔ retrieves the session ID from the cookie
    authenticate()
      ✔ calls the server to get a token and then logs the user into the system
    logout()
      ✔ calls the server to logout the session and expires the session ID cookie
  Gerbera Autoscan
    initialize()
      ✔ clears all fields in the autoscan modal
    addAutoscan()
      ✔ calls the server to obtain autoscan edit load
      ✔ when calling from DB checks for updates
    loadNewAutoscan()
      ✔ using the response loads the autoscan overlay
    submit()
      ✔ collects all the form data from the autoscan modal to call the server
    submitComplete()
      ✔ when successful reports a message to the user and starts task interval
      ✔ when successful for one-time scan reports message to user
      ✔ when fails reports to application error
  Gerbera Items
    initialize()
      ✔ loads the # of view items based on default(25) when app config is undefined
      ✔ loads the # of view items based on application config
    treeItemSelected()
      ✔ updates the breadcrumb based on the selected item
    transformItems()
      ✔ converts a gerbera list of items to the widget accepted list
    loadItems()
      ✔ does not load items if response is failure
      ✔ loads the response as items in the datagrid
      ✔ loads a pager for items
      ✔ sets pager click to the callback method
      ✔ stores the currently selected tree item
      ✔ refreshes the trail using the response items
    loadItems() for files
      ✔ loads file items by transforming them
    deleteItemFromList()
      ✔ calls the server to delete the item
    deleteGerberaItem()
      ✔ calls the server to delete the item for single item
      ✔ calls the server to delete all the items
    deleteItemComplete()
      ✔ shows error when the delete fails
      ✔ does nothing when delete is successful
      ✔ refreshes the items when successful
    editItem()
      ✔ calls the server to load the item details
    loadEditItem()
      ✔ loads the item details into the fields
      ✔ disables the fields based on the server status
    saveItem()
      ✔ calls the server with the item details
      ✔ calls the server with the `container` details
      ✔ calls the server with the `external_url` details
      ✔ calls the server with the `internal_url` details
      ✔ calls the server with the `active_item` details
    saveItemComplete()
      ✔ reloads items when successfully saved
    addFileItem()
      ✔ calls the server to add the item
      ✔ shows error when add fails
      ✔ shows toast message when add succeeds
      ✔ adds a UI timer to check for updates when successful
    addVirtualItem()
      ✔ should show parent id on form when adding new item but no object id
      ✔ should set parent id on form when adding new item
      ✔ should set form elements to proper values and availability
    addObject()
      ✔ calls the server with the item details to add
      ✔ allows creation of object under root parent = 0 (database)
      ✔ calls the server with the `container` details
      ✔ calls the server with the `external_url` details
      ✔ calls the server with the `internal_url` details
      ✔ calls the server with the `active_item` details
      ✔ when successful adds a GERBERA.Updates UI timer to check for updates later
    retrieveGerberaItems()
      ✔ calls the server for items given correct parameters
    retrieveItemsForPage()
      ✔ sends the page number, items per page, and total items to retreive items
      ✔ properly sets the start when page number is high
    nextPage()
      ✔ calls the server for the next page based on current page
    previousPage()
      ✔ calls the server for the previous page based on current page
  Gerbera Menu
    initialize()
      ✔ binds all menu items with the click event
      ✔ on click of Database calls to load the containers
      ✔ on click of menu, clears items
      ✔ on click of home menu, clears tree and items
      ✔ on click of leave beta destroys elements, and navigates to index.html page
  Gerbera Trail
    initialize()
      ✔ clears any data associated with the trail
    makeTrail()
      ✔ creates a trail of elements given a selected item in the tree
    destroy()
      ✔ removes contents of the trail
    gatherTrail()
      ✔ collects trail data from the tree
      ✔ collects trail data from the tree that has non-numeric IDs
    deleteItem()
      ✔ calls the server to delete the gerbera item
      ✔ reports an error if the delete fails
    makeTrailFromItem()
      ✔ uses and item response to make the trail
      ✔ includes add and edit if item is virtual
      ✔ includes edit autoscan if the item is db and autoscan
    trail click operations
      ✔ when click delete calls Gerbera Item delete
      ✔ when click delete ALL calls Gerbera Item delete with ALL parameter set
      ✔ when click add for fs type calls Gerbera Item add
      ✔ when click add autoscan for fs type calls Gerbera Autoscan add
      ✔ when click add for db type calls Gerbera Items to add virtual
      ✔ when click edit calls Gerbera Item edit
      ✔ when click add autoscan for fs type calls Gerbera Autoscan add
  Gerbera Tree
    initialize()
      ✔ loads the tree view
    loadTree()
      ✔ renders the tree with parent and children
      ✔ does not render the tree when response is not successful
      ✔ clears the breadcrumb and loads the first item on load of a new tree
    transformContainers
      ✔ transforms containers response suitable for treeview load
      ✔ only creates parent when boolean is passed
      ✔ creates badges for autoscan containers
    selectType()
      ✔ calls the server for containers when type is db
      ✔ calls the server for containers when type is db
      ✔ on failure calls the app error handler
      ✔ when type is db, checks for updates
      ✔ when type is fs, does not check for updates
    onItemSelected()
      ✔ updates the breadcrumb based on the click of a item
      ✔ passes gerbera data to the items plugin
      ✔ changes the color of the selected row
    onItemExpanded()
      ✔ calls for child items based on the response
    reloadTreeItem()
      ✔ calls the server to reload tree and generate trail and selects item
    reloadTreeItemById()
      ✔ finds the selected item given only gerbera id and reloads it
    reloadParentTreeItem()
      ✔ reloads the parent item
    getTreeElementById()
      ✔ finds the HTML element given the gerbera id
    onAutoscanEdit()
      ✔ calls the GERBERA.Autoscan add method with the event
  Gerbera Updates
    showMessage()
      ✔ uses toast to display a message to the user
    getUpdates()
      ✔ calls the server check for updates
      ✔ calls the server get for updates when forced
      ✔ updates the current task when response from server
      ✔ updates the timer to call back to the server
      ✔ clears the timer if the call to server fails
    updateTask()
      ✔ clears the polling interval when task ID is negative
      ✔ updates the task information if task exists
      ✔ creates a polling interval when tasks still exist
      ✔ passes the response onto the next method
      ✔ passes the response onto the next method when no task exists
    updateUi()
      ✔ when pending UI updates, sets a timeout to be called later
      ✔ when no UI updates, clears the UI timeout
      ✔ when no pending updates, clears the UI timeout
    errorCheck()
      ✔ shows a toast message when AJAX error returns failure
      ✔ ignores when response does not exist
    addUiTimer()
      ✔ uses the default interval to set a timeout
      ✔ overrides the default when passed in
    addTaskInterval()
      ✔ sets a recurring interval based on the poll-interval configuration
    updateTreeByIds()
      ✔ given a failed response does nothing
      ✔ given a response with `all` update ID reloads the whole tree
      ✔ given a response with 1 update ID reloads the parent item of the id
      ✔ given a response with several update ID reloads the parent item for each id
      ✔ clears the update timer when updates are false
      ✔ starts the update timer when updates are pending
  The jQuery Gerbera Autoscan Overlay
    loadItem()
      ✔ loads the autoscan item into the fields
      ✔ marks fields read-only if autoscan is peristent
      ✔ binds the onSave method to the save button
      ✔ shows proper fields for TIMED scan type
      ✔ disables proper fields for NONE scan type
      ✔ hides inapplicable fields for INOTIFY type and shows proper labels
    reset()
      ✔ resets all fields to empty
    saveItem()
      ✔ gives proper data for `TIMED` scan mode to save
      ✔ gives proper data for `INOTIFY` scan mode to save
      ✔ gives proper data for `NONE` scan mode to save
  The jQuery Gerbera Editor Overlay
    addNewItem()
      ✔ defaults fields based on type
      ✔ makes object type enabled and not readonly
      ✔ defaults editable fields when item selected
      ✔ defaults editable fields when active_item is selected
      ✔ defaults editable fields when external_url is selected
      ✔ defaults editable fields when internal_url is selected
      ✔ binds the onSave event to the Add button
    reset()
      ✔ should reset fields to empty
      ✔ should hide parent and object ID fields
    loadItem()
      ✔ should set fields in editor for `container`
      ✔ should set fields in editor for `item`
      ✔ should set fields in editor for `active_item`
      ✔ should set fields in editor for `external_url`
      ✔ should set fields in editor for `internal_url`
      ✔ binds the onSave event to the save button
    saveItem()
      ✔ gives proper data for `item` object to save
      ✔ gives proper data for `container` object to save
      ✔ gives proper data for `external_url` object to save
      ✔ gives proper data for `internal_url` object to save
      ✔ gives proper data for `active_item` object to save
    addObject()
      ✔ gives proper data for `item` object to add
      ✔ gives proper data for `container` object to add
      ✔ gives proper data for `external_url` object to add
      ✔ gives proper data for `internal_url` object to add
      ✔ gives proper data for `active_item` object to add
  The jQuery Datagrid
    ✔ creates a table based on the dataset provided
    ✔ binds the delete icon click to the method provided
    ✔ does not bind delete on file system types
    ✔ binds the edit icon click to the method provided
    ✔ does not bind edit on file system types
    ✔ binds the download icon click to the method provided
    ✔ does not bind download on file system types
    ✔ binds the add icon click to the method provided
    ✔ does not bind add icon to db types
    ✔ creates a table with a footer container a pager
    ✔ creates a pager with only page count pages
    ✔ creates a pager with only necessary amount of pages
    ✔ creates a pager with existing number of pages
    ✔ does not create a pager when no page info exists
    ✔ does not create a pager when no page info exists
    ✔ creates a pager that goes to specific page when clicked
    ✔ creates a pager that goes to previous page when clicked
    ✔ creates a pager that goes to next page when clicked
  The jQuery Gerbera Toast Message
    show()
      ✔ displays the toast message and invokes callback after animation
    showTask()
      ✔ displays the task message
      ✔ has specific task style
  The jQuery Trail
    ✔ Uses an array of items to build the breadcrumb
    ✔ should display in the proper order
    ✔ generates add icons when configured
    ✔ does not generate add icons when not enabled by configuration
    ✔ generates delete icon when enabled by configuration
    ✔ binds the delete icon click to the method provided
    ✔ binds the delete all icon click to the method provided
    ✔ does not generate delete icons when not configured
    ✔ binds the add icon click to the method provided
    ✔ binds the add autoscan icon click to the method provided
    length()
      ✔ reports the length of the trail of items
    items()
      ✔ returns the list of items
    destroy()
      ✔ removes all contents of the parent
  The jQuery Tree
    ✔ creates a list the same size as the data
    ✔ items are loaded in folder closed state
    ✔ binds the item title text to a onSelection method
    ✔ binds the folder title to a onExpand method
    ✔ appends badges to the item
    ✔ binds autoscan edit to the autoscan badge
    ✔ appends the gerbera ID as a data item
    ✔ recursively appends children based on data lineage
    appendItems()
      ✔ given a parent item append children as list
    clear()
      ✔ removes all contents of the tree
    closed()
      ✔ determines whether a node is closed
    collapse()
      ✔ given a parent item append children as list
    select()
      ✔ selects an item by changing the style
    getItem()
      ✔ stores the item data and finds given id
      ✔ clears data after regenerating the tree and loads the new data
    getElement()
      ✔ finds the HTML element given gerbera data item

Finished in 2.921 secs / 2.83 secs @ 15:58:17 GMT-0500 (EST)

SUMMARY:
✔ 216 tests completed

Process finished with exit code 0
```

**Comment by elmodaddyb** [comment]
Unit test code coverage:
gerbera-code-coverage

**Comment by elmodaddyb** [comment]
I plan to fork the `gerbera.io` site to provide further UI documentation.  From a design perspective it built out like below:

`gerbera.<feature>.js` - contains code relevant to capability
`jquery.gerbera.<feature>.js - contains UI element code relevant to capability

I just recently finished the `gerbera.updates.js` which is probably the most complicated and risky(client-side) behavior.  It creates intervals and timeouts to call the server for updates.  If the interval or timeout is not terminated properly, there is no MAX_LIMIT to call....so this could use some extra eyes.

Overall the style & layout is `OK`.  Its basic bootstrap.  I struggled a bit with the 100% height elements.  Any suggestions for improved UI would be greatly appreciated.

**Comment by v00d00** [comment]
Awesome. Lets merge it. Can always fix up issues as they are found.

👍 👍

**Pull request merged**
