### PR TITLE
Make Ffmpg thumbs permanent resources

### PR DESCRIPTION
**Pull request by KarlStraussberger**
Display thumbs as fanart images also via Upnp.

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
Event without this PR I'm not able to watch pictures in Kodi.

**Comment by KarlStraussberger** [comment]
> 
> 
> Even without this PR I'm not able to watch pictures in Kodi.

I was convinced that I once ago used Kodi to browse my images. The forums tell me differently [No Pictures Library](https://forum.kodi.tv/showthread.php?tid=313059&pid=2575700#pid2575700)

**Comment by whyman** [comment]
Nice! Taglib next?

**Comment by KarlStraussberger** [comment]
> Nice! Taglib next?

It already populates `albumArt`. I've got thumbs everywhere now, except pictures that do not have embedded thumbs.

**Pull request merged**
