### PR TITLE
remove some double pointer magic

### PR DESCRIPTION
**Pull request by neheb**
Return the value instead.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
Are you not creating a pointer to an object allocated on the stack and then returning it? What happens to the object then?

I guess RVO is saving you here, because in my head this shouldnt work :shrug:

**Comment by neheb** [comment]
I guess so. But neither coverity nor compilers are complaining.

**Comment by neheb** [comment]
Just saw this pattern used in another codebase. No issues there.

**Comment by KarlStraussberger** [comment]
The semantics of the former code is to leave `pClientInfo` untouched if nothing was found. With your change it is set to `nullptr`.

I'd love to keep this if we need to call `getInfo` for a second time outside the constructor.

**Pull request closed without merging**
