### PR TITLE
consolidate mime type base functions in new mime class

### PR DESCRIPTION
**Pull request by pamapa**
- behind libmagic is a small database, avoid reopening it all the time
- consolidate mime type function

### CODE REVIEW

**Comment by whyman** [comment]
I like the renames for sure, much nicer and the handling of the magic cookie is a good idea.

Im not so sure on passing the ContentManager as a shared pointer to every handler, mostly because the handlers dont "own" the contentManager. I am aware we abuse the shared pointers a lot because of history, but lets try to be clearer with it now.

Would it be sensible to create a new `Mime` class that can manage the libmagic lifecycle and provide these methods? Then we can pass that into anyone who needs mime-stuff?

**Comment by pamapa** [comment]
good idea i will adapt the code to do so.

**Comment by pamapa** [comment]
- the metadata handler only get the Mime object
- all classes which inherit from RequestHandler now only get content object (they needed it be for too), the others (config, database, mime) are then taken via content. This highly simplifies a lot of constructors. The alternate would be to pass along the Mime object through all those constructors too, which sucks.

**Comment by pamapa** [comment]
ready to be merged

**Comment by KarlStraussberger** [comment]
That really looks great. Object orientation moves in!

Maybe we can promote `Server` to the mentioned context class.

**Comment by whyman** [comment]
Really nice work.

I would be keen for the new context class, and to keep the number of things in it as small as possible to reduce coupling.

Also wondering about using [observer-ptr](https://github.com/martinmoene/observer-ptr-lite) to make the ownership explicit.

**Comment by pamapa** [comment]
ok i will provide a patch for the new context class later, i think this can be merged independently....

**Pull request merged**
