### PR TITLE
run through include-what-you-use

### PR DESCRIPTION
**Pull request by neheb**
Add clang-format flag to align comments

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by whyman** [comment]
I like the icwyu, not a fan of the comment alignment.

We would have to add a CI check to enforce it or it would get ignored

**Comment by neheb** [comment]
how so? It's a clang-tidy check.

**Comment by neheb** [comment]
Rebased.

**Comment by whyman** [comment]
Looks good now it doesnt mess with the other comments :+1:

**Comment by whyman** [comment]
@neheb whats the plan here?

**Pull request closed without merging**
