### PR TITLE
Move filesystem function to grb_fs

### PR DESCRIPTION
**Pull request by KarlStraussberger**
Reduces tools mixture

### CODE REVIEW

**Comment by neheb** [comment]
To fix the CodeQL warning I had a patch before that used fmt::output_file. Reason it wasn’t merged was because it required a minimum of 7.1 or something. Now that the minimum has been bumped, could be worth looking at.

**Comment by KarlStraussberger** [comment]
I'd like to create one or two file functions to get rid of all those warnings

**Comment by KarlStraussberger** [comment]
Seems that I managed to obstruct CodelQL's view on the issue which is good for now.

**Comment by whyman** [comment]
Nice!

Feel free to merge once the conflicts are sorted

**Comment by whyman** [comment]
Squashed it instead

**Pull request merged**
