### PR TITLE
Scripting: Log stacktrace on errors

### PR DESCRIPTION
**Pull request by cweiske**
Resolves: https://github.com/gerbera/gerbera/issues/2913

### CODE REVIEW

**Comment by cweiske** [comment]
@KarlStraussberger Build for ubuntu 18.04 failed: https://github.com/gerbera/gerbera/actions/runs/7237253434/job/19716682780
That probably means that this function is not available in their old duktape version.

**Comment by KarlStraussberger** [comment]
That means we have to add some `#ifdef`

**Comment by cweiske** [comment]
I don't have enought C knowledge to do that.
All I know is that `[duk_safe_to_stacktrace](https://duktape.org/api#duk_safe_to_stacktrace)` was added in duktape version 2.4.0: https://duktape.org/api#taglist-2.4.0

There is a `DUK_VERSION` constant, but I don't know how to compare versions in `#if`: https://duktape.org/guide#versioning.4

**Comment by KarlStraussberger** [comment]
See #2921

**Pull request merged**
