### PR TITLE
some code cleanups

### PR DESCRIPTION
**Pull request by neheb**
Uses remove() instead of erase(). Not too sure this works as intended.

### CODE REVIEW

**Comment by neheb** [comment]
OK soooo, it turns out that changing std::list to std::deque or std::vector is enough to fix. Interestingly enough, this is the only usage of std::list in the codebase. I'm not particularly sure why.

**Comment by whyman** [comment]
Can you write some tests for this? I dont have confidence to merge it as it stands.

**Comment by neheb** [comment]
Since I ended up littering code cleanups here, I'll put the list removal in a different PR.

**Comment by neheb** [comment]
Going to split these.

**Pull request closed without merging**
