### PR TITLE
Fedora installation.

### PR DESCRIPTION
**Pull request by limburgher**

### CODE REVIEW

**Comment by whyman** [comment]
Awesome, thanks!

Could you add it to the docs too?

**Comment by limburgher** [comment]
Which did you have in mind?

**Comment by whyman** [comment]
This page: https://github.com/gerbera/gerbera/blob/master/doc/install.rst

**Comment by limburgher** [comment]
That's the file this PR addresses.

**Comment by whyman** [comment]
Sigh, my assumption was you had added it the readme! Deary me

**Pull request merged**
