### PR TITLE
Add documentation and template for Apache/NGinx as reverse proxy

### PR DESCRIPTION
**Pull request by KarlStraussberger**
taken and adapted from #1511

### CODE REVIEW

**Comment by Sithuk** [comment]
Continuing the discussion from #1511, I've added the following to the Gerbera conf. I still get the white frame outlines with a mediatomb graphics placeholder at the top.

    <port>55555</port>
    <virtualURL>http://gerbera.lan/</virtualURL>
  </server>

Nginx conf:
server {
    listen 80;
    server_name gerbera.lan;

    location / {
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_pass         http://gerbera.lan:55555/;

    }
}

**Comment by KarlStraussberger** [comment]
take a look at the apache example and convert the details as in https://www.nginx.com/resources/wiki/start/topics/examples/likeapache/

Also: forward to ip to avoid loops

**Comment by KarlStraussberger** [comment]
In made some tests and updated the example. It worked perfectly on my system.

The subfilter module offers complete rewrite of all content!

**Comment by Sithuk** [comment]
I've used your config as my /etc/nginx/conf.d/gerbera.conf and I still get the same page with white frame borders and a mediatomb placeholder graphic at the top.

I have installed gerbera in a Ubuntu 20.04 lxd container. "nginx -V" includes the "--with-http_sub_module" parameter (see below). I notice you typed to use the subs module (ngx_http_subs_filter_module.so) and not the sub module (ngx_http_sub_module). Was that a typo? I installed the subs module anyway in case that was the problem (sudo apt install libnginx-mod-http-subs-filter). I tried putting the load module line at the top of /etc/nginx/nginx.conf (load_module /usr/lib/nginx/modules/ngx_http_subs_filter_module.so;), but got the following error when I tried to restart nginx (Job for nginx.service failed because the control process exited with error code.). Running "nginx -t" gives the following error description: nginx: [emerg] module "ngx_http_subs_filter_module" is already loaded in /etc/nginx/modules-enabled/50-mod-http-subs-filter.conf:1

Any ideas?

nginx -V:
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-KTLRnK/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-compat --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module

/etc/nginx/conf.d/gerbera.conf:
server {
    listen gerbera.lan:80;
    server_name gerbera.lan;

    location / {
        proxy_set_header   Host               $host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host   $host:$server_port;
        proxy_set_header   X-Forwarded-Server $host;

        # install sub filter module and enable in nginx.conf
        # load_module /usr/lib64/nginx/modules/ngx_http_subs_filter_module.so;
        sub_filter_once    off;
        sub_filter_types   text/html application/json;
        sub_filter         'http://192.168.1.200:55555' 'http://$host:$server_port';

        proxy_pass         http://192.168.1.200:55555/;
    }
}

**Comment by KarlStraussberger** [comment]
Seems that ubuntu inserts the module imports automatically. Just check `nginx.conf`. It very likely contains something like `Include modules-enabled/*.conf`. So you don't have to include it anymore.

**Comment by KarlStraussberger** [comment]
You did correctly install the sub-filters!

**Comment by Sithuk** [comment]
I thought so. Unfortunately the webui didn’t load. It was still loading the white frame borders with no content.

**Comment by KarlStraussberger** [comment]
I am confused by the mediatomb placeholder. It's been changed some years ago. What version do you run? How did you install it?

**Comment by Sithuk** [comment]
The Gerbera version provided in the latest Ubuntu LTS (20.04) repo is v1.1.0. That is what I have installed. I will try installing a more recent Gerbera version from the "stephenczetty/gerbera-updates" repo later.

**Comment by KarlStraussberger** [comment]
Stephen may not be the latest anymore.

See: https://docs.gerbera.io/en/latest/install.html#ubuntu-mint

**Comment by KarlStraussberger** [comment]
FIrst of all you should ensure that gerbera works correctly. I.e. without password prompt. Run `gerbera --create-config` and compare with your `config.xml`.

In order to avoid network issues, specify the network interface (like `eth0`) in you config. Also remove the trailing slash from the `virtualUrl` (should not be a problem, but to be clean). I assume you already added the multicast network (although it should not affect the web ui). Ensure that the gerbera user has ownership of `/etc/gerbera` and everythin in it.

nginx may come with two dirs `conf.d` and vhosts.d in that case use `vhosts.d`

I'm running on openSuSE 15.2 but most of the stuff I'm using is far from out of the box (and there is still the topic for me to create a proper package).

**Comment by Sithuk** [comment]
Thank you for the suggestions. I can access the webui perfectly, without a u/n or p/w using IP:PORT (192.168.1.200:55555). I think that means Gebera is working ok?

**Comment by Sithuk** [comment]
I wonder if there is a conflict between navigating by hostname.DOMAIN (gerbera.lan) and setting virtualURL to gerbera.lan?

**Comment by KarlStraussberger** [comment]
You have to make sure that nginx loads the config in correct order. So create vhosts.d and mv gerbera.conf there.

Add `include vhosts.d/*.conf` before the last `}` in `nginx.conf` and disable other server entries on port 80.

If you still have problems, check `/var/log/nginx/error.log` or similar.

**Comment by Sithuk** [comment]
> 
> 
> You have to make sure that nginx loads the config in correct order. So create vhosts.d and mv gerbera.conf there.
> 
> Add `include vhosts.d/*.conf` before the last `}` in `nginx.conf` and disable other server entries on port 80.
> 
> If you still have problems, check `/var/log/nginx/error.log` or similar.

Creating the vhosts.d directory and loading the config from there made no difference unfortunately. I got a 502 page load error when I tried to access gerbera.lan. I've changed over to apache and have got that working using an adapted version of your apache config. I hope to post more details later.

**Comment by Sithuk** [comment]
If it helps someone, I've created a script to install gerbera on Ubuntu 20.04 and setup a reverse proxy using apache webserver. The reverse proxy removes the need to type the port number to access the WebUI. Thank you to @KarlStraussberger for the Apache config script.
https://gitlab.com/-/snippets/2134172

**Pull request merged**
