### PR TITLE
Fixed use of freed memory

### PR DESCRIPTION
**Pull request by ytimenkov**
What a bummer. 2 persons working on the same fix late night...

#911

### CODE REVIEW

**Comment by ytimenkov** [comment]
That has some other improvement... One bug I found is that `directory_iterator` should take error_code otherwise it throws and exception (permission denied to read `/root`) and just shows nothing.

**Comment by ytimenkov** [comment]
We need a 3rd version of a fix 🤣

**Comment by whyman** [comment]
Darn! Thanks for your efforts though

**Comment by ytimenkov** [comment]
Shall we close this one? (or apply on top? :D)

I think I may consider myself an algorithm nerd 😊 If something can be done more efficiently for free why not do it?..

**Comment by ytimenkov** [comment]
Another thought... Sorting by binary id may be not desired. I made tuple to explicitly contain file name first (comparison is faster than lexicographically traverse long paths with same prefix). But most importantly or can be easily turned into case-insensitive one. Not sure how all binary id sort non-English unicode code points and characters...

**Comment by ytimenkov** [comment]
Actually (besides copying a string just to take its length) map version encodes "native" path. Hope no one uses KOI8 nowadays 🙂

**Comment by whyman** [comment]
Lets close this one, if you have any parts you want improve, open new a PR :+1:

**Pull request closed without merging**
