### PR TITLE
Clientlist on ui

### PR DESCRIPTION
**Pull request by KarlStraussberger**
Adds Clients Page on UI. Each client detected is displayed on the page with its knwon details

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
grafik
That's how it looks like

**Comment by whyman** [comment]
Looks good. Would be nice to show the quirk names instead of the number though.

**Comment by KarlStraussberger** [comment]
Messed that one up by merging master. Rebuild it!

**Comment by KarlStraussberger** [comment]
> 
> 
> Looks good. Would be nice to show the quirk names instead of the number though.

Token display implemented in new PR

**Pull request closed without merging**
