### PR TITLE
add support for Cygwin

### PR DESCRIPTION
**Pull request by neheb**
std needs the GNU variants for kill(), a bunch of netdb.h stuff, fo
functions, and maybe some others.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
bogus and unrelated failure.

**Comment by KarlStraussberger** [comment]
Do you mind adding a remark in the documentation [doc/compile.rst](https://github.com/gerbera/gerbera/blob/master/doc/compile.rst)?

**Comment by neheb** [comment]
It can't really be built with Cygwin easily (spdlog, fmt, and maybe other libraries are missing).

**Comment by KarlStraussberger** [comment]
Can you make the CMakeLists changes conditional for Cygwin environment?

**Comment by neheb** [comment]
Done.

**Pull request merged**
