### PR TITLE
Mime fix

### PR DESCRIPTION
**Pull request by KarlStraussberger**
nested call leads to checking magic each time

### CODE REVIEW

**Comment by KarlStraussberger** [comment]
@whorfin tends to reduce scanning time on my side to 50% (after 10 minutes already 1/6 of the database size)

**Comment by whorfin** [comment]
@KarlStraussberger I still see timestamps indicating 5-7 sec per audio file, although general startup and getting to where audio file scanning is happening does seem considerably snappier
I've patched by hand, so once there's overall integrated changes and/or version bump i can try again

**Comment by KarlStraussberger** [comment]
> 
> 
> @whorfin tends to reduce scanning time on my side to 50% (after 10 minutes already 1/6 of the database size)

Well it's an improvement but images have fewer data but take some time. It only another 5%.

**Comment by whyman** [comment]
Heh, I had this change in a branch locally too :laughing:

**Pull request merged**
